### ISSUE TITLE
A lock screen dialogue box opens despite not having set a passphrase

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#1]
Received phone today. Inserted SIM, started phone, went through set up, chose English (UK) as the language, set up wifi, personalised with user name of mokmeister, finished set up.
Upon arriving at desktop, looked around for a bit, turned on mobile data. Some time after, the screen went to sleep. When I tried to open, I was presented with a screen lock dialogue box identifying the user mokmeister and looking for a passphrase. None have been set. Tried '0000', '1111', '1234', 'a' and just the enter key (null set in passphrase field). 

Is there a default passphrase to open the lock screen?

**Comment by mokmeister** [comment]
Default passphrase is phablet.

**Comment by NeoTheThird** [comment]
Nonetheless this is a bug, right? I'll have to check if this is the case on other UT devices (have to reset one of mine for that), but if it is, that's a recent regression upstream. Should definitely be fixed before a consumer has to set up his new phone, sets it up, locks it, and never unlocks it again :P
