### ISSUE TITLE
Camera app crashes after using, to restart a reboot is needed

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#103]
UT OTA 16

Sometimes after taking some pictures the Camera app crashes to the desktop.
It is not possible to restart the Camera app. 
Only after a reboot the Camera app starts again.

**Comment by Keneda-ut** [comment]
Do you have HDR activated when it occurs ?

I have a similar issue on MX4, only with HDR active, when no HDR on, never happens.

**Comment by Stevie00911** [comment]
@Keneda-ut 
Thank you for your message.
I have HDR **not** acivated while working with the Camera app.

**Comment by wurzer** [comment]
Please make sure, that you are using OTA-17 stable.
Did you change the resolution or aspect ratio? 
Which resolution do you use for front and back camera?

**Comment by Stevie00911** [comment]
UT OTA 17
Since OTA 17 the Camera app did not crash anymore, so I will close this
