### ISSUE TITLE
MMS not working with preferred provider - Sweden

### ISSUE THREAD

**Issue by spinnster** [HelloVolla/ubuntu-touch-beta-tests#105]
Volla Phone with Ubuntu Touch 16.04 (OTA-16)

Despite Cellular data ON, Wifi OFF and correct APN settings, receiving and sending MMS fails with Hallon (my service provider). 
If I use Halebop (work SIM) instead, I can send and receive MMS.
Any ideas as to why it differs? And is there anything I can do to make Hallon work?

Sending MMS's result in "Failed".
As to receiving nothing comes through.

I am incompetent when it comes to technology, so please let me know if I have failed to provide vital details, or if I have added irrelevant information.

**Comment by stekalb** [comment]
Did you double check your APN settings. Sometimes parts of the settings needs to be done manually. Your provider should have documented the settings needed for sending and receiving mms.

**Comment by spinnster** [comment]
Thank you, yes I did. The details are available on the service provider's website.

**Comment by wurzer** [comment]
Please update to OTA-17 stable.
Could you tell us your provider to check your settings?
Do you use a second SIM for the MMS?
I can confirm, that you can only send and receive MMS for the SIM card, that is activated for cellular data.

**Comment by spinnster** [comment]
Thanks for replying! 

The mobile has automatically updated to OTA-17. How do I find out if it is the stable version?
APN checked with provider, all visible settings are correct.
Only one SIM used.

With cellular data ON, Wifi OFF I still cannot send or receive MMS with my private operator, but now an error message appeared also when it failed to receive an MMS, so that is an improvement. As before sending results in a _Failed_ message.
And as before MMS works with my work SIM.

Please find enclosed APN settings on mobile, from provider and MMS reception failed message.

![apn_mobile_operator_message](https://user-images.githubusercontent.com/84271389/120098493-91983c00-c136-11eb-8103-3a5c758e86bf.png)

**Comment by wurzer** [comment]
To check the stable version:

- Call system settings
- Got to updates
- Click on the gear
- You find the update channel in the list
- With a tap you can go to a selection for switching the channel

Regarding MMS,

I think your MMS settings are wrong. Could you send me the name of the provider and I will check it for you? The Proxy should be an IP address. 

If you have two SIM cards: Please note, that it's a known issue, that MMS only works for the SIM card, that is activated for mobile data access.

**Comment by spinnster** [comment]
Thank you :)

The _stable_ channel is selected for updates.

My provider is [Hallon](https://support.hallon.se/hc/sv/requests/new?brand=hallon).

I only have one SIM card.

**Comment by wurzer** [comment]
I found this source: https://forum.hallon.se/teknisk-support-5/apn-instaellningar-4439

However my colleague told me, that Ubuntu Touch might have a problem, if the APN settings for data and MMS is similar. We will investigate in this issue. 

Did you activate 2G/3G/4G option?

**Comment by spinnster** [comment]
Thanks, the settings that are visible on my phone align with that post.

I have 2G/3G/4G selected.

**Comment by gbdomubpkm** [comment]
Yes, currently it is a problem for me to use the same APN for internet and MMS so as to use MMS. But, even with two different APNs, it is not enough so as to use MMS in a reliable way.
https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/94

**Comment by Pekkari** [comment]
Hi, and sorry for the long wait, I got testing this case during this week, I managed to
make mms works with a combined APN in my local service provider(DNA Finland). I
followed the following steps that I'd like you to try, and I invite you to work them through
together in a call if you lack expertise to make them through:

1. Install [PR-28](https://github.com/ubports/ofono/pull/28), by connecting to the phone with the following commands:
    `adb shell && sudo ubports-qa install ofono 28`
2. Open system settings -> Cellular -> Carrier & APN -> APN
3. Disable all checkbok of APNs available, and press the + symbol in top right side to add a new one.
4. Select Used for: Internet and MMS, and fill the rest of the form with the values of your service provider.
5. Press the top right tick mark to save the APN, and exit system settings.
6. Reboot the phone.

Ignore the fact that after saving the APN it doesn't show up in the system settings, still the application
may know what to do after the reboot. Test to send some MMS, and let me know how it went.

**Comment by gbdomubpkm** [comment]
Hello @spinnster and @stekalb . I advise you to stay on OTA-19 if you want MMS work and probably wait OTA-21. See my comments at the end of https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/94

**Comment by wurzer** [comment]
I only know a rare issue with MMS, if the operator has similar MMS settings for both, network and MMS.

**Comment by Pekkari** [comment]
Hi,

as reported in the other ticket, the solution for this is in the [PR 28](https://github.com/ubports/ofono/pull/28). It should
work out of the box, so please test it and report back if you experience problems.

Thanks!

**Comment by gbdomubpkm** [comment]
Hello here. It should be fine to have a feedback (does it work  for you or not ?) of a test of the last PR 28 on OTA-21. Thanks

**Comment by wurzer** [comment]
MMS services will be shut down by cellular operators during this year.
