### ISSUE TITLE
double tap on fingeprint sensor wakes up device

### ISSUE THREAD

**Issue by stekalb** [HelloVolla/ubuntu-touch-beta-tests#106]
**Details about installed OS version**
dev channel  2021-05-14

**Describe the bug**
double tap on fingeprint sensor wakes up device
I assume it's not intended. For me it wakes up the phone in my pocket from time to time.

**Steps to reproduce the bug**
1. send phone to sleep / turn display off
2. double tab fingerprint sensor
3. phone wakes up

**Expected behavior**
Phone doesn't wake up

**Comment by TartanSpartan** [comment]
I thought the idea was to first tap the sensor to wake it to the lock screen, then tap it again to pass the fingerprint test and unlock it. To protect the sensor from being triggered e.g. through the trouser pocket (by your leg perhaps?) a protective phone case is recommended which will keep a physical buffer spacing the sensor away but still allowing your finger access.

**Comment by stekalb** [comment]
If it's an intended behaviour, it's okay for me.

**Comment by wurzer** [comment]
Yes, it is the intended behaviour
