### ISSUE TITLE
Is Convergence supported on the Volla Phone?

### ISSUE THREAD

**Issue by lhooge** [HelloVolla/ubuntu-touch-beta-tests#107]
**Details about installed OS version**
OTA-17

Hi,
I like the idea of convergence and tried to connect the phone via USB-C adapter to my monitor. 
Unfortunately nothing happened. Should this feature work with the Volla Phone?

In dmesg I can see: 
[147650.104142] usb 1-1: usb_get_descriptor type=1 sz=18
[147650.104345] usb 1-1: USB v1a40:p801
[147650.104388] usb 1-1: usb_get_descriptor type=2 sz=9
[147650.104453] usb 1-1: usb_get_descriptor type=2 sz=25
[147650.106037] hub 1-1:1.0: USB hub found
[147650.106141] hub 1-1:1.0: 4 ports detected
[147650.304872] usb 1-1-port3: hub_port_connect portstatus=0x101 portchange=0x0
[147650.304956] usb 1-1-port3: hub_port_reset delay=10
[147650.376234] usb 1-1.3: new high-speed USB device number 15 using musb-hdrc
[147650.376723] usb 1-1-port3: hub_port_reset delay=10
[147650.464536] usb 1-1.3: usb_get_descriptor type=1 sz=18
[147650.465016] usb 1-1.3: USB v5e3:p610
[147650.465038] usb 1-1.3: usb_get_descriptor type=15 sz=5
[147650.465248] usb 1-1.3: usb_get_descriptor type=15 sz=42
[147650.465731] usb 1-1.3: usb_get_descriptor type=2 sz=9
[147650.466043] usb 1-1.3: usb_get_descriptor type=2 sz=25
[147650.469537] hub 1-1.3:1.0: USB hub found
[147650.469888] hub 1-1.3:1.0: 4 ports detected
[147757.293035] dpidle_timer_wakeup_func: 32 callbacks suppressed
[147758.348414] dpidle_timer_wakeup_func: 32 callbacks suppressed

**Comment by JamiKettunen** [comment]
As far as I know the Volla Phone has no hardware support for display over USB, perhaps @NotKit can confirm; best bet is probably to get [aethercast](https://github.com/ubports/aethercast) working ([tracking issue here](https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/92)) or a similar wireless solution.

**Comment by lhooge** [comment]
ah, ok. Thanks for the information and the alternative.

**Comment by wurzer** [comment]
You should be able to connect a keyboard an mouse via Bluetooth and mirror the screen wireless.
Since the device supports USB-OTG you could also use that standard for accessories. 
This article might be interesting for you https://www.cnx-software.com/2015/08/29/connect-an-android-smartphone-or-tablet-to-a-monitor-usb-keyboard-and-mouse-easily-with-a-displaylink-docking-station/

**Comment by mateosalta** [comment]
i think the drivers to use display link might not be there.

**Comment by mateosalta** [comment]
perhaps there exists one for android? that is probally what support was talking about.

**Comment by Deckweiss** [comment]
I mentioned Ubuntu in my question.

I also tried Volla OS without success. 

The USB OTG hub I have works with Pinephone and Samsung dex

**Comment by mateosalta** [comment]
if it works with the pinephone that is a displayport alt mode adapter, not usb-otg 'display link'

**Comment by Deckweiss** [comment]
I have tried multiple ones.

Can you link me a hub that I should try according to you? I do not find anything when I search for "usb c otg diaplaylink"

**Comment by wurzer** [comment]
For Volla OS, a combination of software and hardware should work:

https://www.displaylink.com/downloads/android
https://www.displaylink.com/products/universal-docking-stations

Alternatively you can use wireless screen mirroring.

**Comment by wurzer** [comment]
The challenge is the hardware. We are in contact with our manufacturer to have the USB 3.1 protocol in the future. However I'M convinced, that a wireless solution is more convenient.

**Comment by Deckweiss** [comment]
I have a NexDock and my ultimate goal with all of this is to have a smartphone that I can do some basic programming on without having a full laptop.

Since the NexDock has no brains, it is rather not convenient at all to try and set it up wirelessly.

**Comment by wurzer** [comment]
I have a Superbook of Sentio here to test it with the Volla Phone. This should work. You can find this product on eBay. 

I'm afraid NextDock is only supporting HDMI over USB 3.1. But maybe you can ask NextDock for a solution for devices with USB 2.0 and USB-OTG.

**Comment by mateosalta** [comment]
for volla os

> For Volla OS, a combination of software and hardware should work:
> 
> https://www.displaylink.com/downloads/android
> https://www.displaylink.com/products/universal-docking-stations
> 
> Alternatively you can use wireless screen mirroring.
 for volla os yes, but i believe the software/firmware is not there on ubuntu touch - so no i do not think there is any convergance solution avaible for ubuntu touch on the volla phone yet

**Comment by wurzer** [comment]
For Ubuntu Touch the convergence use case is implicit. You can use the UT Tweak Tool from the Open Store to change to a window mode. Keyboard and Mouse can be connected via bluetooth or USB-OTG. Screen mirroring is only possible wireless. I use VNC for demonstrations.

**Comment by mateosalta** [comment]
> For Ubuntu Touch the convergence use case is implicit. You can use the UT Tweak Tool from the Open Store to change to a window mode. Keyboard and Mouse can be connected via bluetooth or USB-OTG. Screen mirroring is only possible wireless. I use VNC for demonstrations.

most asking are refering to convergance as 'second screen output'

**Comment by wurzer** [comment]
The recent Volla Phone model does not support an HDMI over USB-C, because it only supports the USB 2.0 and USB-OTG protocol. You can use a DisplayPort connection with Volla OS. Unfortunately there is no similar app for Ubuntu Touch, that enables DisplayPort output. 

https://www.displaylink.com/products/universal-docking-stations
https://www.displaylink.com/downloads

There is an app for Ubuntu. So someone may investigate in the compatibility to Ubuntu Touch. It is for Ubuntu 20.04. So after the major update of Ubuntu Touch. The convergence setup could work with thr Volla Phone and Volla Phone X.

https://www.synaptics.com/products/displaylink-graphics/downloads/ubuntu

**Comment by Fuseteam** [comment]
Uh displayport ≠ displaylink, displayport should work with Ubuntu Touch, displaylink however does not...........yet

Some time ago i have filed a support request for ubuntu touch here: https://support.displaylink.com/forums/287786-displaylink-feature-suggestions/suggestions/37143457-add-support-for-ubuntu-touch

**Comment by wurzer** [comment]
DisplayLink is available for Ubuntu but not yet for Ubuntu Touch. Miracast may have a good chance for implementation. For now, one can use the VNC Server app from the open store to mirror the screen.
