### ISSUE TITLE
Optimal functioning of the Volla under UT : battery >= 10 % of its full charge required

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/ubuntu-touch-beta-tests#110]
On every channel, former OTA and last stable.

10% is the minimum battery charge where all the functions of the Volla are more or less accessible and usable: access to the system parameters, reboot... Below this threshold, the Volla may have various malfunctions. Is this minimum threshold of optimal use of 10% normal ? 

To put it in perspective, the BQ E5 HD keeps all its functioning with a quasi-discharged battery.

**Comment by Stevie00911** [comment]
I can confirm this behaviour on my Vollaphone, too.
Under 10% battery charge, no access to system parameters and others.

**Comment by wurzer** [comment]
Please add steps to reproduce. What is in particular not working?

**Comment by gbdomubpkm** [comment]
I haven't gone below 10% for a long time. But to test, for example, try accessing the system settings options and/or changing them and see if you can or try restarting/rebooting the Volla when the battery is bellow 10 %.

**Comment by ma0py** [comment]
This was on Volla Phone X too. System setting app just spinning and close it self. Connecting charger system setting opens, disconnect charger and system settings wont work. battery below 10%. 
But now it's ok for some ota ago, system settings opens on low battery.

**Comment by JamiKettunen** [comment]
I just saw this on the Volla Phone 22 after it had drained to 5%, I couldn't open battery system settings until I plugged in; oddly enough simply plugging in once made it launch fine again even after unplugging while still at the same 5% battery.

**Comment by gbdomubpkm** [comment]
Confirms that recharging the Volla below 10% re-opens the system settings, **but** unplugging the recharging and the problem is back.
The Volla is therefore not reliably usable below a 10% charge, which requires recharging this threshold reached.

**Comment by gbdomubpkm** [comment]
I imagine that this bug will never be fixed under Xenial now. But is it present under focal ?

**Comment by wurzer** [comment]
OTA-25 is the last Xenial update. From OTA-3 of Focal, we can work on further features.

**Comment by gbdomubpkm** [comment]
https://gitlab.com/groups/ubports/porting/reference-device-ports/android9/volla-phone/-/issues to use if there is this bug in focal ?

**Comment by JamiKettunen** [comment]
@gbdomubpkm Correct :)

**Comment by wurzer** [comment]
Sure, I suggest a feature request for an extended battery management under Ubuntu Touch.
