### ISSUE TITLE
cryptsetup not working -- userspace crypto interface not available (algif_*)

### ISSUE THREAD

**Issue by sirrosh** [HelloVolla/ubuntu-touch-beta-tests#114]
**Details about installed OS version**
Ubuntu 16.04 (2021-11-16) on Development channel.

**Describe the bug**
cryptsetup refuses to work because of lack of userspace cipher interface.
Kernel cipher support seems sufficient:
```
phablet@ubuntu-phablet:~$ grep name.*aes /proc/crypto|cut -d : -f 2
 cmac(aes)
 ecb(aes)
 cbc(aes)
 aes
 xts(aes)
 ctr(aes)
 cbc(aes)
 ecb(aes)
 __xts-aes-ce
 __ctr-aes-ce
 __cbc-aes-ce
 __ecb-aes-ce
 aes

```
but any operation fails with the same reason: "Userspace crypto wrapper cannot use cipher_name (-95)"
The benchmarking, being less specific, throws the suggestion:

```
phablet@ubuntu-phablet:~$ cryptsetup benchmark
# Tests are approximate using memory only (no storage IO).
PBKDF2-sha1       297890 iterations per second
PBKDF2-sha256     185129 iterations per second
PBKDF2-sha512     168907 iterations per second
PBKDF2-ripemd160  263196 iterations per second
PBKDF2-whirlpool   61134 iterations per second
Required kernel crypto interface not available.
Ensure you have algif_skcipher kernel module loaded.
```

**Steps to reproduce the bug**
1. Install cryptsetup with an apt tool
2. Run cryptsetup benchmark
3. '...'

**Expected behavior**
```
$ sudo cryptsetup benchmark
# Tests are approximate using memory only (no storage IO).
PBKDF2-sha1       698119 iterations per second for 256-bit key
PBKDF2-sha256     879677 iterations per second for 256-bit key
PBKDF2-sha512     657002 iterations per second for 256-bit key
PBKDF2-ripemd160  438367 iterations per second for 256-bit key
PBKDF2-whirlpool  302706 iterations per second for 256-bit key
argon2i       4 iterations, 609520 memory, 4 parallel threads (CPUs) for 256-bit key (requested 2000 ms time)
argon2id      4 iterations, 617027 memory, 4 parallel threads (CPUs) for 256-bit key (requested 2000 ms time)
#     Algorithm |       Key |      Encryption |      Decryption
        aes-cbc        128b       119.7 MiB/s       138.0 MiB/s
    serpent-cbc        128b        47.5 MiB/s       186.4 MiB/s
    twofish-cbc        128b       117.7 MiB/s       151.9 MiB/s
        aes-cbc        256b        95.7 MiB/s       107.7 MiB/s
    serpent-cbc        256b        47.5 MiB/s       186.4 MiB/s
    twofish-cbc        256b       117.7 MiB/s       151.9 MiB/s
        aes-xts        256b       141.2 MiB/s       140.1 MiB/s
    serpent-xts        256b       171.4 MiB/s       178.2 MiB/s
    twofish-xts        256b       147.1 MiB/s       149.9 MiB/s
        aes-xts        512b       110.5 MiB/s       109.7 MiB/s
    serpent-xts        512b       171.4 MiB/s       178.2 MiB/s
    twofish-xts        512b       147.0 MiB/s       149.9 MiB/s

```

**Comment by JamiKettunen** [comment]
Appears to indeed be a kernel module isssue, [`CRYPTO_USER_API_SKCIPHER` that is](https://cateee.net/lkddb/web-lkddb/CRYPTO_USER_API_SKCIPHER.html).

What does `zcat /proc/config | grep CRYPTO_USER_API_SKCIPHER` show? If it's `=m` does a `modprobe algif_skcipher` help?

**Comment by sirrosh** [comment]
> Appears to indeed be a kernel module isssue, [`CRYPTO_USER_API_SKCIPHER` that is](https://cateee.net/lkddb/web-lkddb/CRYPTO_USER_API_SKCIPHER.html).
>

Yes, it indeed is. I started threads on multiple forums including [manufacturer's](https://forum.volla.online/viewtopic.php?f=41&t=250), but nobody cares.
 
> What does `zcat /proc/config | grep CRYPTO_USER_API_SKCIPHER` show? If it's `=m` does a `modprobe algif_skcipher` help?

It is not set.

I [asked](https://forum.volla.online/viewtopic.php?f=41&t=251) for the kernel build configuration, but the result was predictable (nobody cared to answer). 
I presume that was all done at wrong places, otherwise it would looked like a poorely maintained/supported device...

P.S.: I'm ready to help solving this, if someone will support me.

**Comment by sirrosh** [comment]
P.P.S.:
I came from Linux world, so it's not a problem for me to configure and build the right kernel and/or modules for any existing architecture. But that Halium thing is completely new for me, as I'm pretty far from understanding the system's layering, booting process etc.

However it's never too late learning something ;)

**Comment by JamiKettunen** [comment]
The kernel source can be found at https://github.com/HelloVolla/android_kernel_volla_mt6763 (defconfig: `arch/arm64/configs/k63v2_64_bsp_defconfig`) but isn't exactly straight forward to compile. It doesn't compile stand-alone due to never being tested for that so you'll need to get a whole Halium build tree setup just to `mka halium-boot`, https://github.com/HelloVolla/local_manifests has some notes for this in case you're interested.

**Comment by sirrosh** [comment]
Yes, I am very interested, thank you!
/proc/config seemed to be incomplete, that's why I started a thread on volla forum. Then I realized that it does not use the pure Linux kernel like some other platforms.

Is there any chance that volla's original kernel dev team post an updated build or this phone is destined to die with that 4.4.146+ it had initially?

Thanks again for your time.

**Comment by wurzer** [comment]
Ubuntu Touch doesn't support encrypted user data yet. It's device independent requirement. I suggest to post this requirement on the board of the generic Ubuntu Touch development. It will probably on the agenda after the 20.04 update.

**Comment by sirrosh** [comment]
Very roughly speaking, ubports (or Ubuntu Touch as per your reference) is a Unity8 (lomiri) GUI over the linux kernel, correct?
Therefore it is incorrect to say, that ubports has no "user data encryption feature", it just lacks the GUI support for it, because the 4.4 linux kernel has this feature by default and one can use it with a help of cryptsetup suite -- a de-facto standard toolset for managing encrypted partitions. The simpliest bash script (even mentioned on the [official ubports forum](https://forums.ubports.com/topic/1012/one-method-to-encrypt-home-phablet)) will encrypt your whole userspace volume **but only** if the userspace crypto interface is turned on in the kernel.

**And for the unknown and unexplainable (for now) reason someone deliberately turned it off in Volla kernels.**

That's what I'm talking about here.

**Comment by sirrosh** [comment]
Thank you for your answer.

It's a pity, you did not comment on the sentence written in bold. I would really like to know why Volla kernel builder deliberately disabled the ability to use the kernel crypto interface for its users?

For me personally this would be a 100% no-no factor and I would never buy this phone if I know it beforehand. There are devices with the same or higher maturity level and much better hardware than this Chinese GIGASET thing.

**Comment by wurzer** [comment]
Thanks for your reply. We didn't disable the encryption feature in the Kernel to prevent the use of encryption. Ubuntu Touch is unfortunately not able to use user data encryption for now. Ubuntu Touch is not a Desktop operating system and wouldn't be able to use that feature.
