### ISSUE TITLE
Issues with OTA 21

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#116]
Here I colleceted some issues, which occur with the newly released OTA 21:

- Camera app does not open anymore; reboot needed.
- Audio volume gets only half as loud as normal; reboot needed.
- After a reboot audio comes out of the internal speaker instead out of the plugged in headphone. 
- SD card is not recognized anymore; reboot needed.
- The video app stops playing a video after the screen lock is activated.
   Before OTA 21 the video app runs without being stopped.  

All that occured after 2 days of using the Vollaphone with OTA 21.
I have the impression that the more new OTAs come, the more the Vollaphone gets worse supported.

**Comment by gbdomubpkm** [comment]
Hello. Maybe you should also open a thread on the forum to draw attention and for confirmation by users of the points you mention. Few people come to github.

**Comment by Stevie00911** [comment]
Now we are on OTA 22 und further problems will be reported via an extra issue.
