### ISSUE TITLE
Halium 10 RC - Autobrightness doesn't work

### ISSUE THREAD

**Issue by j2g2rp** [HelloVolla/ubuntu-touch-beta-tests#117]
Ubuntu 16.04 2022-W06
Autobrightness doesn't work. The toggle doesn't change to automode. You still can use the bar to adjust brightness manually.

**Comment by gbdomubpkm** [comment]
https://github.com/orgs/ubports/projects/32#column-17291341 for Switch Volla X to halium 10 is probably a good place to speak of that.

**Comment by JamiKettunen** [comment]
This has been fixed on Ubuntu Touch 20.04, no idea about 16.04 (and it is also end of life now so new changes won't be getting in anymore)
