### ISSUE TITLE
Halium 10 RC - Bluetooth can't be dissabled

### ISSUE THREAD

**Issue by j2g2rp** [HelloVolla/ubuntu-touch-beta-tests#119]
Ubuntu 16.04 2022-W06
Bluetooth can't be disabled through system settings or indicator. It keeps enabled.

**Comment by ma0py** [comment]
Same at ota-22 
VollaPhone X

**Comment by IanHasman** [comment]
In a discussion on the ubports forum domubkpm pointed out that you could kill the daemon by typing

sudo service bluetooth stop

In a terminal. That stops your battery being wasted if you don't want to use BT. If you want BT back on then type

sudo service bluetooth start

In the terminal then power down the phone and turn it back on again.

**Comment by IanHasman** [comment]
My log for indicator-bluetooth has only one entry and it reads

** (process:22071): WARNING **:
killswitch.vala:103 : Can't open /dev/rfkill for use as a killswitch backend: no such file or directory

Is that the indicator switch or a physical kill switch for devices that have them? I have a Volla Phone X with no physical kill switches.

**Comment by IanHasman** [comment]
And every time I try to slide the BT control to off I get 

** (process:22071): WARNING **:
killswitch.vala:61: Could not write rfkill event: Bad file descriptor
