### ISSUE TITLE
Volla - Not possible to register a fingerprint

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/ubuntu-touch-beta-tests#121]
I can't register a fingerprint !  I am on RC 50 (OTA-22). In fact it did not work in OTA-21 for me. I have never tested in a lower OTA.
Does it work for you ?? Does the fingetprint reader work ?
If yes, how do you proceed IN DETAIL to register your fingerprint? I can't get it to work and a recurring message after a delay that the reader doesn't work.
Thanks in advance for feedbacks.

**Comment by gbdomubpkm** [comment]
@wurzer Hello. Does it work for you ?

**Comment by wurzer** [comment]
Yes, with OTA-22 it is now possible to use the fingerprint sensor on both devices, Volla Phone and Volla Phone X.

**Comment by gbdomubpkm** [comment]
How to proceed EXACTLY to register a fingerprint ?? It doesn't want to work for me.

**Comment by wurzer** [comment]
You can follow the following screen flow

![01](https://user-images.githubusercontent.com/7789612/157078070-a2e71886-45b1-42f9-a92c-cfdd704d030a.png)
![02](https://user-images.githubusercontent.com/7789612/157078085-26f77911-ae76-4b9a-9952-645ade279ab9.png)
![03](https://user-images.githubusercontent.com/7789612/157078091-ec0c8ab0-4f1e-4f16-aded-8a356268b54f.png)
![04](https://user-images.githubusercontent.com/7789612/157078093-172635f9-55a2-48dc-855c-2bbdff38dc5e.png)
![05](https://user-images.githubusercontent.com/7789612/157078095-57b03bf7-9826-48d2-ae07-545e96d38f2f.png)
![06](https://user-images.githubusercontent.com/7789612/157078097-af26d965-3ddc-41c8-a067-5d366266bfd2.png)
![07](https://user-images.githubusercontent.com/7789612/157078100-5fd122e4-4742-401f-8fa6-05e2503f8dce.png)
![08](https://user-images.githubusercontent.com/7789612/157078101-553f85ea-5466-48b1-92c1-216719329566.png)
![09](https://user-images.githubusercontent.com/7789612/157078103-aed1b026-cf46-4d3c-84c9-d356eba34310.png)
![10](https://user-images.githubusercontent.com/7789612/157078106-2fdaa44e-ab12-4bbb-99e4-4f4ff5c3af40.png)

**Comment by gbdomubpkm** [comment]
Is this working test with the Volla (not the Volla X) ?

Thanks for the procedure but i was not accurate enough.  What I would like to know is how much finger movement is required (thumb) and in what direction for the fingerprint to register and for how long.

**Comment by wurzer** [comment]
These are screenshots from my Volla Phone X with OTA-22

**Comment by gbdomubpkm** [comment]
> These are screenshots from my Volla Phone X 

So this does not prove that the fingerprint sensor for the Volla, not volla X, works. Did you test on Volla ?

**Comment by gbdomubpkm** [comment]
I apologise. IT WORKS VERY WELL. It's my fault, I didn't do the right thing and I won't tell you what.... 😉😁 The only thing that remains is the Dark Mode non-support which does exist.

**Comment by wurzer** [comment]
I love the Suru Dark Theme. You can activate it with UT Tweak tool from Open Store

**Comment by gbdomubpkm** [comment]
I speak of fingerprint reader. See bottom of screenshots:

![screenshot20220308_131604760](https://user-images.githubusercontent.com/50362604/157237270-2c2f0a54-24d3-4347-98ea-cff19a73019b.png)
Ambiance theme (we see delete/next)

![screenshot20220308_131514438](https://user-images.githubusercontent.com/50362604/157237276-6dacbad7-12f6-44cd-9c1a-26f9d061cab9.png)
Suru dark theme (we don't see delete next)

**Comment by wurzer** [comment]
Ah, you mean, that the bottom background is not changed to dark. It was defined as a static color. The label with white font on white background is invisible in this case. Yes, this should be fixed.
