### ISSUE TITLE
Device page for VP22 on ubuntu-touch.io

### ISSUE THREAD

**Issue by svenha** [HelloVolla/ubuntu-touch-beta-tests#127]
Now that more and more VP22s are used, can we ask for a device page on ubuntu-touch.io, similar to https://devices.ubuntu-touch.io/device/yggdrasilx/ ?

**Comment by JamiKettunen** [comment]
Yes, this is something I've started but have yet to finish due to other more critical tasks requiring time. I'll update this issue once I make a merge request to https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io hopefully next week :)

**Comment by gbdomubpkm** [comment]
What channels does the volla 22 currently operate on?
Briefly, would it be possible to know what is not working yet?

**Comment by GerryT11** [comment]
> Briefly, would it be possible to know what is not working yet?
This might help: https://github.com/HelloVolla/ubuntu-touch-beta-tests/wiki/High-level-epic-overview-for-Ubuntu-Touch-port

**Comment by gbdomubpkm** [comment]
Hello.
Many users are waiting for this: when will the Volla 22 be (functional) in the installer ?

**Comment by Bolly** [comment]
> Hello. Many users are waiting for this: when will the Volla 22 be (functional) in the installer ?

I reinstalled it because it wouldn't start. I think it is now functional.

https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/77#issuecomment-1250366949

**Comment by svenha** [comment]
@Bolly Which version of the UBports installer did you use?

**Comment by Bolly** [comment]
> @Bolly Which version of the UBports installer did you use?

0.9.7 ;)

**Comment by svenha** [comment]
Thanks. I can only find a beta version: https://github.com/ubports/ubports-installer/releases

**Comment by JamiKettunen** [comment]
@svenha Looking at [the UBports installer tagged versions](https://github.com/ubports/ubports-installer/tags) there has not been a single stable release yet so [the latest beta](https://github.com/ubports/ubports-installer/releases/latest) is the best we have for now.

The current devices page of the device will look like https://deploy-preview-410--ubports-ubuntu-touch-devices.netlify.app/device/mimameid/ once https://gitlab.com/ubports/infrastructure/devices.ubuntu-touch.io/-/merge_requests/410 is merged, let me know if things that are missing or wrong!

**Comment by D-9x** [comment]
Hi, does anybody know if it is possible to install Ubuntu Touch instead of Volla OS via UBports-installer (from Ubuntu desktop) on Volla 22?
The device is listed on the manual configuration in the UBports application (desktop) but isn't yet listed on the website: 
https://devices.ubuntu-touch.io/
At the moment I'm running Ubuntu Touch on SD card in dual boot with Volla OS (android) on the internal storage.

**Comment by JamiKettunen** [comment]
@D-9x check My message just above yours, the device page is just about finalized and should be merged soon-ish. and yes [the UBports installer](https://devices.ubuntu-touch.io/installer/) does have support to (re)flash Ubuntu Touch on the Volla Phone 22 with support sometime soon also coming to flash SailfishOS or Volla OS as well :)

**Comment by D-9x** [comment]
@JamiKettunen thanks a lot. That's a great news! :) I'll certainly flash Ubuntu Touch on it as only OS, I've been waiting to have it on a phone for years. ;) 
Cool there'll be the option to install SailfishOS and VollaOS as well.

**Comment by gbdomubpkm** [comment]
>  I'll certainly flash Ubuntu Touch on it as only OS

Hello @D-9x 
If it's your only smartphone, not sure it's a good idea right now 😉 : Volla OS is very secure, much more functional than UT on the Volla 22 and therefore Volla OS can be of great service to you i think 🙂

**Comment by gbdomubpkm** [comment]
Hello @JamiKettunen
Should we update the Volla to the most recent version of Volla OS available through the system settings before flashing UT with the installer ?

**Comment by JamiKettunen** [comment]
@gbdomubpkm That should be no problem, it'll only be a problem a bit later when we need to update the UBports installer firmware bootstrap archive to contain Android 11 firmware when Android 12+ based Volla OS comes around.

**Comment by D-9x** [comment]
@gbdomubpkm Thank you for the advise. Yes it's my only phone and I've been using it for a bit more than a week now but I can tell you I love UT (despite few minor issues here and there) and honestly I didn't expect to find it "perfectly baked" otherwise I'd have chosen the mainstream thing. ;)
I've been using GNU/Linux on desktops for years and totally support the philosophy behind it, I just have to remember Ubuntu Touch isn't Ubuntu Desktop. :D

Anyway I've received a reply from Volla Support Team (which I contacted before writing here) and they told me that the difference of performance between UT on the EMMC (internal storage) or on the SD card in multiboot is barely noticeable (of course if the SD is good). If I decide to keep Volla OS it might be for emergency but I'm using only UT anyway. :)

By the way does anyone know when 20.04 will be released?

**Comment by JamiKettunen** [comment]
@D-9x 20.04 will boot on the Volla Phone 22 when https://gitlab.com/ubports/porting/community-ports/android11/volla-phone-22/volla-mimameid/-/merge_requests/1 is merged so you can enable notifications on that if you want (assuming you have signed in).

As for when it'll be usable as a daily driver that might still take some time, talking maybe some 4 months, no exact time frame still as it's a bit hard to predict the challanges of the ongoing upgrade.

**Comment by D-9x** [comment]
@JamiKettunen Thanks for the info! :)

**Comment by gbdomubpkm** [comment]
> @gbdomubpkm That should be no problem, it'll only be a problem a bit later when we need to update the UBports installer firmware bootstrap archive to contain Android 11 firmware when Android 12+ based Volla OS comes around.

Ok. Thank you.
Another question to clarify : at this stage, is the Volla 22 more mature than the community port under ubuntu 20.04 of other smartphones like the Volla for example? In short, does the Volla 22 partly follow a different path?

**Comment by JamiKettunen** [comment]
Now live at https://devices.ubuntu-touch.io/device/mimameid/, enjoy!

**Comment by JamiKettunen** [comment]
> Ok. Thank you. Another question to clarify : at this stage, is the Volla 22 more mature than the community port under ubuntu 20.04 of other smartphones like the Volla for example? In short, does the Volla 22 partly follow a different path?

@gbdomubpkm I've not actually checked how well 20.04 works at all on Volla 22 myself, so no idea. About different path it tries to keep compatability with 16.04 without having to make another branch for the main device configuration repo so in that sense I suppose it's unique, don't know if others needing changes have done something similar but the Volla Phone X at least didn't and [has a separate branch here](https://gitlab.com/ubports/porting/community-ports/android9/volla-phone-x/volla-yggdrasilx/-/tree/focal).
