### ISSUE TITLE
ADB does not work in system

### ISSUE THREAD

**Issue by NeoTheThird** [HelloVolla/ubuntu-touch-beta-tests#13]
Only works in recovery. Developer mode has no effect.

**Comment by JamiKettunen** [comment]
ADB should now work after OTA to build 2020-08-30. For future reference, commits [ff1f6c5](https://github.com/HelloVolla/android_device_volla_yggdrasil/commit/ff1f6c55d90f42e089222f83a9f867ac41cebbf8)...[a6bedb9](https://github.com/HelloVolla/android_device_volla_yggdrasil/commit/a6bedb93bd42516ab261c8616a2ad7ed63879357) (3 in total) made it work.
Note that it seems you have to reboot the device in order for developer mode state to actually change the USB mode.

**Comment by 0312birdzhang** [comment]
It's working well both on windows and deepin linux, version Ubuntu 16.04 2020-09-05.
