### ISSUE TITLE
Volla Phone 22 crashes and screen turns orange after fiddling with the GUI

### ISSUE THREAD

**Issue by pnguyen9** [HelloVolla/ubuntu-touch-beta-tests#135]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

Ubuntu 16.04 2022-08-18/2

### Describe the bug

I was trying to make MMS work again (it worked for a short instant) by configuring APN. It worked in 3G and not in 4G, then suddenly, it stopped working in 3G too.

Sometimes, when I try to uncheck APN, I feel like it's not taken into account (i.e. even though I unchecked the Internet access related APN, I still have access to Internet).

I started hitting the reset APN configuration button several times, which then resulted in the phone losing Internet connection, even when I try to re-enable the Internet related APN. After fiddling a little more (unchecking, rechecking, reset APN, etc.), the phone screen turned black, white, black and then ended stuck on an orange screen.

![191329246-30532c54-1112-47bc-a4a0-4cb7431f035a](https://user-images.githubusercontent.com/22443655/191355387-7f23a748-e614-4f8d-a943-94d709e95682.jpg)

The only thing left to do then was to keep the power button pressed until it shut down and then I restarted the phone.

Eventually, I realised the only way for modified APN to be taken into account is to reboot the phone after every changes, which is when I finally managed to send MMS with 4G. 

Related issue: I had to use a separate APN for Internet and MMS, because whenever I tried choosing "Internet and MMS", it reverted to "Internet" whenever I saved, but not much of a problem.

### Steps to reproduce the bug

- Slide down from the top of the screen.
- Open Network tab (you need a SIM card).
- Open "Mobile settings..."
- Open "Carrier & APN"
- Open "APN"
- Start fiddling around until mobile data stops working and the phone eventually crashes (check/unchex the APN, spam the Reset All APN Settings button, etc.)

Another easy way to make it happen:
- Open the top menu by sliding down.
- Make sure Wi-Fi is disabled.
- Double-tap within a half a second interval to enable and disable Wi-Fi right away.
- The screen will turn black for a while before becoming orange.

### Expected behaviour

- The checkbox is supposed to allow to enable/disable APN.
- APN changes should be taken into account without having to reboot the phone
- The phone shouldn't turn into lemonade.

**Comment by Idcrafter** [comment]
it happened to me as i just turned off wifi as it tried to show me the available ones, the UI crashed and than rebooted into the Orange screen

**Comment by JamiKettunen** [comment]
This is very easily reproducible by quickly trying to switch the Wi-Fi toggle continuously, but not so much if you do the steps a bit slower.

Best workaround for now is to toggle the Wi-Fi enabled state a bit slower while we figure out the issue on kernel driver side. From `/proc/last_kmsg` logs after rebooting the problem [appears to be somewhere around here](https://gitlab.com/ubports/porting/community-ports/android11/volla-phone-22/kernel-volla-mt6768/-/blob/halium-11.0/drivers/misc/mediatek/connectivity/wlan/core/gen4m/mgmt/ais_fsm.c#L1111-1152).

**Comment by JamiKettunen** [comment]
Can someone confirm if this is still happening on 16.04 OTA-24?

**Comment by pnguyen9** [comment]
It looks like it's working for me. Another way I could reproduce this was to disable Wi-Fi while Hotspot was enabled (now it's working fine).
