### ISSUE TITLE
The Volla Phone 22 may reboot when you try to take a screenshot

### ISSUE THREAD

**Issue by pnguyen9** [HelloVolla/ubuntu-touch-beta-tests#136]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

~~Ubuntu 16.04 2022-08-18/2~~
Ubuntu 16.04 OTA-24

### Describe the bug

Sometimes, when I long press the power button and choose the screenshot button, the screen turns white and then the phone reboots. Upon rebooting, if I try to take a screenshot again, the phone reboots again.

### Steps to reproduce the bug

- Long press the orange power button on the right.
- Choose to take a screenshot when the modal appears.
- The phone will either reboot or take a screenshot.

### Expected behaviour

A screenshot should be taken instead of a reboot.

**Comment by JamiKettunen** [comment]
Are you sure you didn't accidentally tap on `Restart` instead of `Screenshot`? They're right next to each other in the power menu and I cannot reproduce this issue even on the same version with Ubuntu Touch as a secondary system on SD card.

**Comment by pnguyen9** [comment]
Hmm... I'm practically sure that I don't, because the kind of reboot that I get isn't the same as when I tap on the reboot button. I will have to try again while recording myself just in case.

**Comment by pnguyen9** [comment]
It seems like it's working perfectly fine now and I can take screenshots by pressing on the sound buttons as well as going through the power button menu. I'm closing this issue.

**Comment by pnguyen9** [comment]
I'm reopening this issue because it just happened again as I was about to take a screenshot on my phone, and it seems to be happening every time I try to take a screenshot (just like last time). After the reboot, the screenshot folder is still empty, which means nothing was taken.

Oddly enough, it's not like a full reboot either (it didn't ask me to unlock the sim card like it usually does when I reboot my phone).

@JamiKettunen Is there a way I can share the recording so that it's only available for Volla? 

Edit: And now it started working again. I'm going to try to understand what I did differently to reproduce it.

**Comment by JamiKettunen** [comment]
I'm guessing this "reboot" is really the shell crashing then, as in when it "reboots" you just immediately see the Ubuntu Touch loading screen and not the Volla logo on a black background?

**Comment by pnguyen9** [comment]
@JamiKettunen Yeah, and the "desktop" appears much faster than a real reboot too.

**Comment by JamiKettunen** [comment]
I'm still unable to produce the issue on OTA-24 with holding both volume buttons or using the power menu > Screenshot option, would be great if you can provide a copy of `~/.cache/upstart/unity8.log` here and perhaps also the `unity8.log.1.gz` in case the log already got rotated after the shell process crash (which is rather likely).

**Comment by pnguyen9** [comment]
I'm also having trouble to reproduce it. It decided to start working properly again.

The crashes started happening around Wednesday 7th December 1:40 CET (when I was trying to take screenshots). The video attempt was recorded at 1:43.

I'm seeing this kind of error appearing 3 times around that time in the first file (which fits my 3 attempts):

> Object 0x2229eca0 destroyed while one of its QML signal handlers is in progress.
> Most likely the object was deleted synchronously (use QObject::deleteLater() instead), or the application is running a nested event loop.
> This behavior is NOT supported!
> file:///usr/share/unity8//Components/Dialogs.qml:277: function() { [native code] }
> ()

[unity8.log](https://github.com/HelloVolla/ubuntu-touch-beta-tests/files/10171917/unity8.log)
[unity8.log.1.gz](https://github.com/HelloVolla/ubuntu-touch-beta-tests/files/10171918/unity8.log.1.gz)

**Comment by pnguyen9** [comment]
Screenshots seem to be working fine so far on 20.04, so I'm closing this.

**Comment by floss-user** [comment]
I have experienced the reboot issue just today on a freshly installed Volla 22 with freshly installed UT to the microSD card with multiboot. First three times I pressed that Screenshot button, the phone rebooted immediately. Then I learned about the other way to take a screenshot by pressing both volume buttons at once. This worked, and from then on, I could also take a screenshot from the power button menu without problems.

I have just reported this here: [UBports Gitlab](https://gitlab.com/ubports/development/ubuntu-touch/-/issues/2249)

**Comment by wurzer** [comment]
@floss-user Are you on OTA-9 for UT as a primary OS?

**Comment by floss-user** [comment]
I'm on a fresh install of Volla OS 14 (the phone was purchased with UT) and installed UT to the SD card the day before yesterday. How can I identify which OTA I'm on? In the settings I find the following information:

<img width="540" height="585" alt="Image" src="https://github.com/user-attachments/assets/12dc6a88-f44e-4341-8587-013e4f63a89a" />

Just this morning I went back to the Volla Boot Manager. It allowed me to update the UT installation but the version information shown here remained the same as before. It seems to have installed the same version over again.

I didn't experience the reboot problem while I was on native UT on the same device, but I haven't used it in a while before flashing Volla OS. I can't say for certain whether it only happens with UT as secondary OS.

**Comment by wurzer** [comment]
You are using an outdated version, that is not maintained any more. Please update Ubuntu Touch in the multi boot manager and make sure, that your are using the recent version of Volla OS

**Comment by pnguyen9** [comment]
There may be a problem with the update feature of the multi boot manager, because like @floss-user , every time I try to update Ubuntu Touch, it always says there's a new version available to download.

**Comment by floss-user** [comment]
I'm still struggling to find out what UT version I'm exactly running. As I said, I installed it from the Volla Boot Manager as secondary OS to microSD card just a couple of days ago.

In the UT system settings, it says: "Last Updated 14.07. 24". I believe this would have been after the release of OTA-9:

<img width="540" height="585" alt="Image" src="https://github.com/user-attachments/assets/28a33e84-672b-40dc-a905-7ff78434704f" />

On the more detailed version info page in the settings, I don't know how to relate any of those numbers to a specific OTA release:

<img width="540" height="585" alt="Image" src="https://github.com/user-attachments/assets/2e82dc81-5080-49f7-ab3c-f9504ec13f16" />

Standard Linux commands are putting out information about the underlying Ubuntu, but nothing specifically about UT:

```shell
phablet@ubuntu-phablet:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
phablet@ubuntu-phablet:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal
phablet@ubuntu-phablet:~$ hostnamectl
   Static hostname: ubuntu-phablet
   Pretty hostname: Volla Phone 22
         Icon name: computer-handset
           Chassis: handset
        Machine ID: <redacted>
           Boot ID: <redacted>
  Operating System: Ubuntu 20.04.6 LTS
            Kernel: Linux 4.19.191-g09c22cd8fafa
      Architecture: arm64
phablet@ubuntu-phablet:~$ cat /etc/*release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
phablet@ubuntu-phablet:~$ 
``` 

Can someone help me determine which version of UT I'm running?

**Comment by floss-user** [comment]
In the meanwhile, on my previously mentioned Gitlab issue, we have established that it's not a full reboot, it's just Lomiri crashing:

https://gitlab.com/ubports/development/ubuntu-touch/-/issues/2249

I have published two logs there: one during a crash, and one while it was working. Perhaps somebody could make sense of the differences between the to logs.

**Comment by wurzer** [comment]
That looks like a generic issue, not device specific. @JamiKettunen
