### ISSUE TITLE
Volla Phone 22 reboots occasionally since last Android Update

### ISSUE THREAD

**Issue by krauzalat** [HelloVolla/ubuntu-touch-beta-tests#142]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

VollaOS 11.1

### Describe the bug

Before the last VollaOS Update on August 23rd 22 I had massive lagging issues. That's fixed since the update perfectly, thanks a lot!

But since this Update, my phone reboots about twice a week (on average). That issue is most likely to happen while using the phone playing media like videos or music. The screen just turns black for a short moment, the phone reboots and the lockscreen appears.

### Steps to reproduce the bug

Most of the times I would be watching videos on youtube, using the Fennec browser, using the signal app or spotify app.

### Expected behaviour

It should not randomly reboot :)

**Comment by JamiKettunen** [comment]
Hey, this repository is specifically for the Ubuntu Touch port, please create this issue again on https://github.com/HelloVolla/volla-os-beta-test, thank you.

**Comment by krauzalat** [comment]
Sorry, my fault.
