### ISSUE TITLE
File explorer has trouble with screen rotation when displaying a preview of a JPEG

### ISSUE THREAD

**Issue by pnguyen9** [HelloVolla/ubuntu-touch-beta-tests#144]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

Ubuntu 16.04 2022-08-18/2

### Describe the bug

I've only tested it on JPEG although I think it might be the case with all kind of images. I haven't tested on other type of files though (PDF maybe?).

When you open an image preview through the file manager, it displays properly in portrait and landscape view. However, if you rotate from portrait to landscape after having opened the image preview, it will freeze for a short moment, and when the rotation happens, the image disappears.

Since I'm using dark theme, it shows a black background.

### Steps to reproduce the bug

- Unlock your phone rotation if it's locked.
- Download an image into your phone.
- Open File Manager.
- Navigate to where you downloaded the image.
- Rotate your phone into portrait view, the select the image and choose Preview. A preview of the image will be visible at the top of the screen.
- Rotate your phone into landscape view. The application will remain frozen for a short while before the rotation happens, and the image disappeared.
- Rotate back into portrait view. The image is back.
- Press the "<" back button in the upper left corner.
- Rotate your phone into landscape view, then select the image and choose Preview. A preview of the image will be visible.
- Rotate your phone into portrait view. The preview is still visible, but instead of appearing at the top, it's appearing in the middle of the screen.
- Rotate your phone into landscape view. The same thing happens as if you opened the preview in portrait view.

### Expected behaviour

The file manager should be able to rotate the view without the image preview disappearing.

**Comment by JamiKettunen** [comment]
Hey, things like this make sense to first report to the upstream repository where they're seen properly, i.e. in this case https://gitlab.com/ubports/development/apps/filemanager-app/-/issues, and later an issue created here in case it turns out to be some device specific issue.

Please do let me know if this issue should be re-opened later!
