### ISSUE TITLE
Opening m4v in media player fails with "Error playing video" message.

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#15]
Opening a m4v file fails with an error message as follows:
"Error playing video
Failure connecting with playback backend."
the error message is accompanied by a close button. Hitting the close button returns you to the calling application (eg. file manager, teleports etc.)

**Comment by mokmeister** [comment]
Same file opens and plays properly using UTmedia application.

**Comment by NotKit** [comment]
Can it be still reproduced on latest update?

**Comment by mokmeister** [comment]
Media player now opens and plays m4v files. However, the loud speaker is not used so audio is hard to hear. Different issue.
