### ISSUE TITLE
Opening .mov file in media player produces "Error playing video" message

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#16]
Opening a mov file fails with an error message as follows:
"Error playing video
Failure connecting with playback backend."
the error message is accompanied by a close button. Hitting the close button returns you to the calling application (eg. file manager, teleports etc.)

**Comment by mokmeister** [comment]
Same file opens ok with UTmedia app.

**Comment by wurzer** [comment]
I  can't reproduce this issue. You may provide an example file. Please note that .mov is just a container format. I may contain any encoding that is not supported by Ubuntu Touch.

**Comment by JamiKettunen** [comment]
As we've not heard back from you for a long while I'll go ahead and close this. In case you still have this issue please comment or create a new issue about it (including more information / sample file)! :)
