### ISSUE TITLE
[20.04] Automatic brightness option unavailable

### ISSUE THREAD

**Issue by buchnerh** [HelloVolla/ubuntu-touch-beta-tests#161]
### Is this a new report?

Yes

### Device model

Volla Phone (2020)

### OS version

20.04 devel R403

### Describe the bug

There is no setting for activating to automatic screen dimming / brightness in focal. Under 16.04 Xenial it was there and working. Other phones (e.g. Pixel 3a) seems to have the auto brightness feature under 20.04 already, so it seems that it's device-specific.

### Steps to reproduce the bug

1. Go to System-Settings->Brightness
2. There should be an option to enable "auto adjustment" but there's only the slider for the static brightness

### Expected behaviour

1. Go to System-Settings->Brightness
2. There is on top a slider for the brightness-level
3. Beneath there is an option to activate "auto adjust the brightness"

**Comment by buchnerh** [comment]
@JamiKettunen  The automatic brightness is working, but it seems that after pressing the power button the screen comes up with the last brightness-level, then lower the brightness to minimum and a few seconds later set the correct brightness-level. So you can read the screen the first time approximitely after 5 seconds. If I remember correctly, under Xenial the brightness was set correctly. My second phone (BQ E4.5 with Xenial) also doesn't show this behaviour.

**Comment by JamiKettunen** [comment]
@buchnerh The issue you mentioned was fixed with https://gitlab.com/ubports/development/core/repowerd/-/merge_requests/71 and should be in latest 20.04 RC/Development channel builds as of 4 days ago :)

**Comment by buchnerh** [comment]
@JamiKettunen I've already seen that it's fixed some days ago and I think it's working like under xenial again. Thanks to you and ratchanan :)
