### ISSUE TITLE
[16.04] On Volla Phone 22, after enabling Hotspot and using it for heavy browsing on a computer, the phone can no longer connect to a Wi-Fi connection until rebooted

### ISSUE THREAD

**Issue by pnguyen9** [HelloVolla/ubuntu-touch-beta-tests#163]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

Ubuntu 16.04 (OTA-24)

### Describe the bug

I have been sharing my mobile phone connection with my laptop so that I could work with a stable connection, when I could not have access to a stable wired/wireless connection.

The other day, I realised I have been having trouble connecting to some Wi-Fi connections; including those with which I had no trouble connecting to in the past.

After rebooting my phone and trying again, it came to my understanding that it might have something to do with my enabling the Hotspot to share my mobile data with my laptop.

### Steps to reproduce the bug

- Reboot the phone to start from scratch.
- Unlock your phone.
- (Disable your mobile data if it's running.)
- Enable Wi-Fi and choose a network which works. You should be able to browse some websites or some online apps.
- (Unlock your SIM card if it's not already done.)
- Enable your mobile data.
- Enable Hotspot and connect to the shared Wi-Fi connection with another device.
- On the other device, start browsing on some heavy websites such as Youtube for a short while (I used Firefox).*
- Disable hotspot on the phone, then disable your mobile data.
- If you look at the icons at the top, you should notice an empty network triangle, even though the selected Wi-Fi connection appears green. From this point on, when I try to connect to any Wi-Fi connection, nothing happens.
- The only solution is to reboot the phone.

*: I tried to open Microsoft Teams on Chromium on my laptop to read some messages, which allowed me to reproduce the bug on the phone. But after enabling and disabling plane mode, I was able to get the Wi-Fi connection to work again, whilst when I browsed Youtube, the plane mode solution no longer worked.

### Expected behaviour

The phone should be able to connect to a Wi-Fi connection, after disabling a Hotspot Wi-Fi connection that was heavily used.

**Comment by pnguyen9** [comment]
I'm closing this ticket because the last release for 16.04 was OTA-25 and there is no hotspot on 20.04 yet.

**Comment by JamiKettunen** [comment]
Hotspot does work on 20.04 but only without password currently so feel free to try how it works there already (and report issue against the following repository if the problem still happens). There's a workaround for enabling password too in https://gitlab.com/ubports/porting/reference-device-ports/android11/volla-phone-22/volla-mimameid/-/issues/2#note_1337771125 if you dare try it before the relevant merge requests are done :)
