### ISSUE TITLE
[20.04] On reboot, if you only have 1 sim card inside slot 1 and nothing in slot 2, the Volla Phone 22 cannot detect it

### ISSUE THREAD

**Issue by pnguyen9** [HelloVolla/ubuntu-touch-beta-tests#165]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (2023-W13)

### Describe the bug

I had updated my Volla Phone 22 to OS version 20.04 after switching to the stable build channel at the beginning of the month, and so far it was working to my satisfaction.

Today, when I rebooted my phone to fix MMS issues, all of a sudden, the phone started telling me it could not detect any sim card, and asked me to insert one before rebooting the phone.

I removed and re-inserted the sim card into the slot 1 before retrying, but it was still telling me it could not detect a sim card.

Workaround: Slot 2 is still functional. And after a reboot with the sim card in slot 2, it can then be moved into slot 1, which will now detect it.

### Steps to reproduce the bug

- Open the back of the phone.
- Insert one sim card into slot 1 and nothing in slot 2.
- Reboot the phone.
- If you open the top Network menu, the Cellular data option should be greyed out and no sim card is displayed.
- Open mobile settings.
- There should be an error message saying that no sim card could be detected, and prompting you to insert one before rebooting the phone.
- Open the back of the phone again if you closed it.
- Switch the sim card from slot 1 into slot 2.
- Reboot the phone.
- If you open the top Network menu, the Cellular data option is now working properly and showing the sim card in slot 2.
- Without rebooting the phone, switch the sim card from slot 2 into slot 1.
- Now the sim card is properly detected in the top Network menu.

### Expected behaviour

Sim card 1 should be detected even if no sim card 2 has been inserted on reboot.

**Comment by JamiKettunen** [comment]
Hey, this sounds like https://gitlab.com/ubports/porting/reference-device-ports/android11/volla-phone-22/volla-mimameid/-/issues/3 which was fixed on 20.04 development update channel a few weeks back and will be included in 20.04 OTA-2.

Please try to report further 20.04 issues on that GitLab page instead as all Ubuntu Touch device port related issues are being migrated there from all vendors (not just Volla), thanks :)
