### ISSUE TITLE
Volla Phone 22 | Issues facing after upgrade to UT 20.04

### ISSUE THREAD

**Issue by Arunkumarprakasam** [HelloVolla/ubuntu-touch-beta-tests#166]
I am using Volla Phone 22 and I upgrade OS from UT 16.04 Stable to 20.04 Stable recently. After upgrated, I noticed below issues,

1. **Network notification:** there was an text as "/hfp/org/bluez/hci0/dev_EC_89_14_B6_63_DD No Sim" & "/hfp/org/bluez/hci0/dev_10_8E_E0_42_E3_3D No Sim". Please refer below image for your reference.
![image](https://github.com/HelloVolla/ubuntu-touch-beta-tests/assets/96546804/75ace1a5-0776-4c47-a9ee-31723b561df4)

2. **Mobile settings:** Under connection type, the SIM 1 and SIM 2 are selected 2G/3G by default and below that, these is Network selection available but not connecting with 4G network.
![image](https://github.com/HelloVolla/ubuntu-touch-beta-tests/assets/96546804/ce07ebbd-2854-4a1d-bbd8-962256d81c95)

3. **Phone Settings:** There are 4 group of "Call waiting, Call forwarding & Services" Please refer below image.
![image](https://github.com/HelloVolla/ubuntu-touch-beta-tests/assets/96546804/f9be740c-9530-4b81-9fd0-94835ff9429b)

4. **Language:** I used Indian Language (especially TAMIL) font in Teleports app & Youtube webapp, but after upgrade to UT 20.04, it was not supporting.

**Comment by JamiKettunen** [comment]
I see you already also created https://gitlab.com/ubports/porting/reference-device-ports/android11/volla-phone-22/volla-mimameid/-/issues/7 which is the correct place for all future 20.04 issues, closing this one.
