### ISSUE TITLE
External display not working on X23?

### ISSUE THREAD

**Issue by tannevaled** [HelloVolla/ubuntu-touch-beta-tests#168]
# Expected behavior:

plug an usb-C display cable and get the external display as additional or mirrored display (convergence mode?).
combined with a bluetooth keyboard+mouse (this part works)

# Actual behavior:

nothing

on the https://devices.ubuntu-touch.io/device/vidofnir the X23 is noted not working with wireless display.
later on the page it is said as not supported feature with wired display.
What is the exact status?
Is their a known problem?
Is it planned to work or is there a blocking reason?

I wanted to test the device with a VR Headset (Pico4 / Meta Quest PRO) plus Immersed.
Immersed for Linux is distributed as AppImage.
Has someone already installed AppImage on Volla Phones?
What should be the *native format* to ask Immersed to distribute for devices like the X23 if AppImage is/won't be supported?

Thanks for your reply.

**Comment by JamiKettunen** [comment]
The devices page mentioned `Wired External monitor` being an unsupported feature for a reason. What exactly is this magical "usb-C display cable"? the phone hardware is a USB 2.0 type-C port which most likely has nowhere near enough bandwidth or a sophisticated enough PHY on the phone side to do what you're attempting even under Android (VollaOS); can you check if this is the case?

**Comment by tannevaled** [comment]
sad ,news. my device comes with Ubuntu Touch installed. i do not have VollaOS to check. but if this is an USB-2 ports, no way it will work. best luck with VR headset.

**Comment by JamiKettunen** [comment]
You can use https://devices.ubuntu-touch.io/installer/ to switch the OS on the device
