### ISSUE TITLE
Double amount of icons on the desktop for the standad apps in English on a German version

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#169]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 Development r500

### Describe the bug

As I am using the German version of Ubuntu Touch, I have the double amout of icons on the dectop for the standard apps in English.
For example, "Android Keyboard", "Browser", "Calculator", "Calendar", "Camera", "Clock", "Files", "Gallery", "Music", "Recorder" and "Settings".
When I click on them nothing happens.
And I cannot delete them.
I added a screeshot of my desktop.

### Steps to reproduce the bug

1. Go to the Desktop

### Expected behaviour

I expect olyy to see the german icons of the standard apps.

### Additional context

![Volla Phone 22 Ubuntu Desktop](https://github.com/HelloVolla/ubuntu-touch-beta-tests/assets/45417818/b73ec3a4-3353-4c27-8a71-bb2ec8e2e716)

**Comment by wurzer** [comment]
It looks like you have installed Waydroid. What you see are Android apps next to Ubuntu Touch Apps.

**Comment by Stevie00911** [comment]
Hello Dr. Wurzer,
thank you for your input to this issue.
I had Waydroid installed and deinstalled a long time ago.
Actually I had only the "Waydroid Helper" app installed.
Now I deinstalled "Waydroid Helper", too, but the English icons are still present on the desktop.
Can you please reopen this issue?
Greetings, Stefan

**Comment by wurzer** [comment]
You screenshot shows Android apps. I conclude, that Waydroid is still installed.

**Comment by Stevie00911** [comment]
No, waydroid is not installed.
As I wrote, it was installed and deleted some month ago.
Maybe the deinstallation routine did not delete the android icons.
But how to delte those icons?
Actually in the OpenStore Waydroid is not presend to install.
So it is not possible to redo the installation und deinstallation process.

**Comment by wurzer** [comment]
Looks like it is not completely removed. I suggest to ask the Waydroid community. @erfanoabdi Do you have an idea?

**Comment by JamiKettunen** [comment]
@Stevie00911 on 20.04 version of WaydroidHelper it has an uninstaller with a wipe option, that'll cleanup the leftover `~/.local/share/applications/*aydroid*.desktop` files along with some others

**Comment by Stevie00911** [comment]
Hi Jami, yes, thank you so much. Your suggestion was the solution. I reinstalled the WaydroidHelper app and could again uninstall Waydroid with this wipe option. Now the the android icons are gone :-) super!
