### ISSUE TITLE
media player fails to open webm file with "Error playing video" message

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#17]
Opening a webm file fails with an error message as follows:
"Error playing video
Failure opening the source video."
the error message is accompanied by a close button. Hitting the close button returns you to the calling application (eg. file manager).

**Comment by mokmeister** [comment]
same content plays ok in UTmedia app.

**Comment by wurzer** [comment]
I can't reproduce this issue. You may offer an example file

**Comment by JamiKettunen** [comment]
As we've not heard back from you for a long while I'll go ahead and close this. In case you still have this issue please comment or create a new issue about it (including more information / sample file)! :)
