### ISSUE TITLE
Volla X23 UT Camera App has wrong GPS metadata in Fotos (I was unable to select X23)

### ISSUE THREAD

**Issue by UT-Fan** [HelloVolla/ubuntu-touch-beta-tests#170]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 focal 2023-W44 OTA-3 (RC7)

### Describe the bug

If you take a picture with a volla X23 with lokation position enabled the photo app store the wrong gps metadata in the picture.

### Steps to reproduce the bug

Take a picture with the UT Photo app with gps location enabled, read the included metadata with mat2 -s. Check the gps position of the metadata and compare it with the gps position where you took the photo. You will find an difference of 50 to 100 km. 

### Expected behaviour

Please check this behavior and correct the photo app to store the right gps metadata in the pictures.

### Additional context

I took a picture at: 52° 40' 12.4" N 13° 19' 0.8"  E
With mat2 -s its shown 53° 20' 12.12" N 13° 36' 58.66" E
I add the picture
![image20231120_134431009](https://github.com/HelloVolla/ubuntu-touch-beta-tests/assets/152421420/d70e3687-e9c4-4b4d-b66c-37bb806b9816)

**Comment by wurzer** [comment]
This is not a device specific issue. Please file the bug to Ubports.
