### ISSUE TITLE
Voice Controll

### ISSUE THREAD

**Issue by dathoschy** [HelloVolla/ubuntu-touch-beta-tests#172]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 OTA-4

### Describe the bug

I miss general voice control in Ubuntu Touch. Calls using the voice function of Bluetooth devices such as a car radio therefore do not work.

### Steps to reproduce the bug

1. Connect to a Car Radio via Bluetooth (worked)
2. push the button for Voice Control on the steering wheel
3. Name the function (make a call)
4. Nothing happens or an acoustic error signal comes

### Expected behaviour

I connect my Volla Phone 22 to my car radio, press the button on the steering wheel for the voice control of the car radio, say who I want to call and an error tone comes and nothing else happens

**Comment by wurzer** [comment]
Ubuntu Touch doesn't support voice control
