### ISSUE TITLE
Snap on multiboot X23

### ISSUE THREAD

**Issue by RinkebyDanceKids** [HelloVolla/ubuntu-touch-beta-tests#173]
High. Unless i missed something lately. You can't install Snap on UT OTA-3. As there need to be a modification for the kernel provided by the phonemaker or specific phone-team. In our case Volla.

So I wonder if I done something wrong? Maybe already implemented. Or perhaps a roadmap. As it is a simple modification.

Thanks!

**Comment by wurzer** [comment]
You want to install desktop apps? Please use the Libertine cotnainer for this purpose.

**Comment by RinkebyDanceKids** [comment]
Hi,

And yes I do. But Snap for UT does now exist with a lot of apps that libertine dont haven nor is libertine any good. So to have this small modification from your side would be great.

**Comment by RinkebyDanceKids** [comment]
To help a bit

https://open-store.io/app/snapz0r.fredldotme


This little helper utility enables the use of Snaps on Ubuntu Touch 20.04.

For proper support make sure to ask your device's maintainer to enable the following kernel defconfig switches:

CONFIG_SQUASHFS=y
CONFIG_SQUASHFS_XZ=y
CONFIG_SQUASHFS_LZO=y

**Comment by JamiKettunen** [comment]
20.04 OTA-4 is out since a few weeks ago and this already should be addressed with https://gitlab.com/ubports/porting/reference-device-ports/halium12/volla-x23/kernel-volla-mt6789/-/commit/dee43dbf

**Comment by RinkebyDanceKids** [comment]
Oh! Look at that! What a interesting way to view changes. And thanks Jami! Then I only need to wait for the multiboot of OTA-4.
