### ISSUE TITLE
Scrolling on Waydroid Jumps and Reverses

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/ubuntu-touch-beta-tests#174]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (OTA-4)

### Describe the bug

Waydroid (System Image 25 May 2024, Vendor Image 25 May 2024)

When I quickly scroll down in Waydroid (in any app/browser), the screen jumps around as if it gets confused on where I am touching it. It even goes as far as scrolling entirely the other way, all the way to the top. The same goes for scrolling up (I end up at the very bottom). I noticed this happens in Waydroid in general, and not in specific apps. I can confirm though that is does happen in Firefox, IMDB, NewPipe and others. I thought at first it was the screen protector, but then I tried scrolling in Morph or Sapot browser in UT (outside of Waydroid), and the scrolling seems fine. 

### Steps to reproduce the bug

1. Access Waydroid (any app/browser) - Firefox, IMDB, NewPipe
2. Scroll down (Quickly)
3. The screen jumps around as if it gets confused on where I am touching it.
4. The screen ends up at the very top
5. The same goes for scrolling up (I end up at the very bottom)

### Expected behaviour

Scrolling is smooth

### Additional context

https://forum.volla.online/viewtopic.php?f=41&t=1196

**Comment by wurzer** [comment]
This shoudl be reported to Waydroid

**Comment by CubedApple** [comment]
> This shoudl be reported to Waydroid

Hi, can you please point me to the right direction? I would like to report at the right place. Thanks

**Comment by JamiKettunen** [comment]
@CubedApple https://github.com/waydroid/waydroid/issues would be the place to report bugs upstream
