### ISSUE TITLE
Waydroid hangs when UT browsers (Morph/Sapot) are open - RAM usage issue?

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/ubuntu-touch-beta-tests#175]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (OTA-4)

### Describe the bug

Waydroid (System Image 25 May 2024, Vendor Image 25 May 2024)

Waydroid hangs or stalls really slowly when UT browsers, such as Morph and/or Sapot are open. When the UT browsers are closed, Waydroid seems to be running smooth again. Perhaps, the RAM is getting full on my Volla Phone 22 when I use both Waydroid and UT browsers at the same time?

### Steps to reproduce the bug

1. Open Morph and/or Sapot browser in UT
2. Open Waydroid
3. Navigate through or use Waydroid normally (access apps, browsers etc - Firefox?)
4. Waydroid screen hangs or gets stuck in loading animation
5. UT still works outside of Waydroid

### Expected behaviour

Waydroid operates smoothly when UT browsers (Morph / Sapot) are also open

### Additional context

https://forum.volla.online/viewtopic.php?f=41&t=1197
https://forum.volla.online/viewtopic.php?f=41&t=1190

**Comment by wurzer** [comment]
This should be reported to Waydroid
