### ISSUE TITLE
Volume level in UT does not match Waydroid when changing volume levels

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/ubuntu-touch-beta-tests#176]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (OTA-4)

### Describe the bug

Waydroid (System Image 25 May 2024, Vendor Image 25 May 2024)

When I click 'volume up/down' on my Volla Phone 22 while outside of Waydroid (or when screen is off), the music playback in Waydroid (for example, Spotube or NewPipe) does not change volume. The problem goes away when I unlock my phone and go into Waydroid to change the volume (even with the side button). However, since I was lowering the audio in UT, the volume in Waydroid stays the same. Therefore, there is now a mismatch in audio. I would then lower the volume to 'mute' to 'reset' the volume to match on both UT and Waydroid. Not a big deal, just an observation that I'm sure most of you are already aware of.

### Steps to reproduce the bug

1. Open Waydroid
2. Play music from Waydroid app (Spotube)
3. Turn off screen OR go outside of Waydroid (into UT)
4. Click volume up or down on the side of the Phone
5. Volume level for UT changes
6. Waydroid volume level DOES NOT change (unless the Waydroid screen is open)

### Expected behaviour

Volume level for Waydroid changes at the same level and time as UT volume even when screen is off or outside of Waydroid

### Additional context

https://forum.volla.online/viewtopic.php?f=41&t=1198

I am not sure if there is a solution to this given the way Waydroid is treated as a separate 'app' inside UT. However, maybe there is a way to 'match' the UT volume with Waydroid? That way, music volume control while playing audio from Waydroid can be controlled while the screen is off.

**Comment by wurzer** [comment]
Shoudl be reported to Waydroid
