### ISSUE TITLE
Waydroid notification sounds crack/stutter in max volume

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/ubuntu-touch-beta-tests#177]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (OTA-4)

### Describe the bug

Waydroid (System Image 25 May 2024, Vendor Image 25 May 2024)

When I get a notification from Waydroid, the sound stutters and cracks. And it seems to always do so at maximum volume. This goes for pretty much every or any app - Outlook, Messenger, Wire, etc. Even when screen is off.

### Steps to reproduce the bug

1. Open Waydroid
2. Receive any notification
3. Notification sound stutters/cracks at max volume (screen can be on or off)

### Expected behaviour

Notification sound from Waydroid is smooth and whole when received either when screen is on or off.

### Additional context

https://forum.volla.online/viewtopic.php?f=41&t=1199
https://forum.volla.online/viewtopic.php?f=41&t=1190

**Comment by wurzer** [comment]
Should be reported to Waydroid
