### ISSUE TITLE
Bluetooth Audio Output Level is Lower than other Devices

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/ubuntu-touch-beta-tests#178]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (OTA-4)

### Describe the bug

When connected to a Car Bluetooth Audio stereo (2008-2012 Subaru Forester in this case), the audio levels seem lower than other devices also connected to the car stereo. Another device I have is the Sony Xperia XA2 Plus with Sailfish OS and that seems to play audio much louder (and clearer) therefore I can keep audio levels in-phone and in-car lower. Whereas, with my Volla Phone 22, the audio levels have to be cranked all the way up to max in-phone and in-car to obtain the same audio output level

### Steps to reproduce the bug

1. Turn on bluetooth in UT
2. Pair with bluetooth device (in car, or headphones etc)
3. Play music using UT 'Music'
4. Listen to audio

### Expected behaviour

Audio levels when played through bluetooth should be loud at medium volume

**Comment by wurzer** [comment]
Won't fix

**Comment by CubedApple** [comment]
> Won't fix

Hi, can you please elaborate? Thanks
