### ISSUE TITLE
Bluetooth in-car info (Battery level, signal strength etc) do not appear in car stereo screen

### ISSUE THREAD

**Issue by CubedApple** [HelloVolla/ubuntu-touch-beta-tests#179]
### Is this a new report?

Yes

### Device model

Volla Phone 22 (2022)

### OS version

20.04 (OTA-4)

### Describe the bug

When I pair my Volla Phone 22 to my bluetooth car stereo(2008-2012 Subaru Forester in this case), the battery info, signal strength etc do not show up on screen. Whereas, when I pair my Sony Xperia XA2 Plus with Sailfish os, OR iPhone SE to the car stereo, it shows up with such information

### Steps to reproduce the bug

1. Turn on bluetooth in UT
2. Pair with bluetooth car stereo
3. Observe that the battery info, signal strength etc are missing

### Expected behaviour

When the VP22 is paired with a car stereo via bluetooth, the phone battery info, signal strength etc should show up.

**Comment by wurzer** [comment]
Won't fix

**Comment by CubedApple** [comment]
> Won't fix

Hi, can you please elaborate? Thanks
