### ISSUE TITLE
Wi-Fi connection

### ISSUE THREAD

**Issue by Mattia990** [HelloVolla/ubuntu-touch-beta-tests#18]
If i'm connected to a network and i enable airplane mode and i disable wifi, i'm not able to see and connect to wifi networks even after a reboot.

P.S Sometimes, when the phone is in idle, it asks for wifi password.

**Comment by Stevie00911** [comment]
And after disabling and re-enabling Wi-Fi, the vollaphone does not reconnect the known Wi-Fi-connection and does not show any list of other existing Wi-Fi connections.

**Comment by Stevie00911** [comment]
And after a reboot Wi-Fi connection turns allways "on".

Ubuntu Version 16.04. (2020-07-24)
