### ISSUE TITLE
Volla Phone Quintus running Ubuntu Touch failes updating to OTA-7

### ISSUE THREAD

**Issue by jojumaxx** [HelloVolla/ubuntu-touch-beta-tests#182]
Since I can't select the Volla Phone Quintus as a model on the Bug Report site, yet, I'm filing this as blank issue which contains all information I have and hopefully all needed.

The Volla Phone Quintus (Ubuntu Touch) was delivered with OTA-6 preinstalled. Shortly after, OTA-7 was released. Installing this update fails. After tapping on "Restart & Update" the Phone reboots and aborts with the following message:

```
Setting up partitions...
E:Failed to find block device for partitionproduct_a
Executing Ubuntu update script...
Error installing Ubuntu update, exit code: 256
Please go to Advanced -> View recovery logs -> /cache/ubuntu_updater.log

```
The content of the mentioned log file is as follows:

```
System Image Upgrader for Ubuntu Touch
Preparing command file
Starting image upgrader
Loading keyring: archive-master.tar.xz
Processing command file
Loading keyring: image-master.tar.xz
Loading keyring: image-signing.tar.xz
umount: /dev/block/dm-1: Invalid argument
umount: /cache/system: Invalid argument
umount: /mnt/system: Invalid argument
e2fsck 1.45.4 (23-Sep-2019)
/dev/block/dm-1 has unsupported feature(s): FEATURE_C12
e2fsck: Get a newer version of e2fsck!

/dev/block/dm-1: ********** WARNING: Filesystem still has errors **********

e2fsck is unable to fix partition/image /dev/block/dm-1, aborting (return code 12)
```

Thanks for taking a look at this

**Comment by JamiKettunen** [comment]
It seems the factory rootfs image was created with a newer `e2fsprogs` which the now rather outdated tools included both in UBports recovery/UT 20.04 can't handle entirely when it comes to running `e2fsck` against system partition as least.

As far as I know the only way (right now) to fix this will be to switch your update channel to something non-stable and then back if you wish, or reflash without data formatting via UBports installer.

**Comment by jojumaxx** [comment]
Yes, switching channels solved this issue. Thank you very much for your help.

**Comment by jojumaxx** [comment]
Yes, switching channels solved this issue. Thank you very much for your help.

**Comment by jojumaxx** [comment]
Yes, switching channels solved this issue. Thank you very much for your help.
