### ISSUE TITLE
Keyboard vibration on has no effect

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#19]
After turning "Keyboard vibration" on the vollaphone, it has no effect.

Ubuntu version 16.04. (2020-07-24)

**Comment by JamiKettunen** [comment]
Keyboard vibration toggle works perfectly fine on `Development` update channel `Ubuntu 16.04 (2020-09-08/2)` build, can you recheck this since it's been a long while since this issue was created?

**Comment by JamiKettunen** [comment]
Closing this as the vibration effect itself works (even though it's quite weak in some places currently).
