### ISSUE TITLE
Phone radio stopts working after a while

### ISSUE THREAD

**Issue by J-Glasswall** [HelloVolla/ubuntu-touch-beta-tests#21]
While testing the UT (16.04 - 2020-07-14) driven Volla phone as a daily driver i have noticed that the GSM radio stops working after a while (somewhere between 24h usage). 
The signal strength of the carrier and data provider keeps at normal levels, but if i get called the caller get instant voicemail, i cant call out neither.
After a reset i receive the SMS's with the missed calls and all works normal, till somewhere between then and 24hrs.

**Comment by wurzer** [comment]
Could you recheck this issue?

**Comment by JamiKettunen** [comment]
This could be another instance of #55, need to check this myself now as well while leaving the phone to idle for a week; if I still see everything working as expected I'll go ahead and close this issue.

**Comment by TellingBerto** [comment]
Hello,

to whom it may concern. 
I had VollaPhone with UT for several month as daily driver and did not recognize this behaviour.
After update to 2020-11-27/2 I realized that cellular data couldn´t be reactivated (cell data was working fine some hours before when turning on the phone in the morning).
- No "3G" indicator in the indicator bar (after activation of the cellular data).   
- No internet connection with Morph.
Workaround: Cell data was available after a reboot. 
Achchha nahee!

**Comment by wurzer** [comment]
Please make sure, that you are on the Stable OTA channel.

**Comment by UniversalSuperBox** [comment]
I believe this issue is the same as https://github.com/ubports/ubuntu-touch/issues/1629, and can be closed as we are tracking it there.

**Comment by JamiKettunen** [comment]
As per Dalton's message I'll go ahead and close this in favor of tracking progress on the UBports issue tracker.
