### ISSUE TITLE
Connecting Vollaphone to a Windows 10 PC via USB cable - no device shown

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#24]
By connecting the Vollaphone to a Windows 10 PC via USB cable there is no device shown in the Windows Explorer.

With an Aquarius E5 and the Ubuntu from UBports this was previously possible.
The standard folders of the Ubuntu phone and an inserted SD card were shown in the Windows Explorer and it was possible to read and write files to the phone's memory. 

However the Vollaphone seems to be charged via the USB cable, even if the battery icon on the Vollyphone shows the "no charging" icon.

Ubuntu version 16.04. (2020-07-24)

**Comment by luka177** [comment]
Duplication of #12

**Comment by 0312birdzhang** [comment]
Is it working now? For me it's working on Linux, but on windows there is just a icon. When i double clicked, a format confirm dialog is displayed.

![image](https://user-images.githubusercontent.com/1762041/92396730-16ca6380-f158-11ea-958e-122be0a61c45.png)

**Comment by 0312birdzhang** [comment]
Okay, i fixed by manually install MTP driver. 

https://www.droidviews.com/fix-mtp-driver-installation-on-windows-10/ 

### 2. Install the MTP USB Device Driver
![图片](https://user-images.githubusercontent.com/1762041/92427405-f97cb000-f1be-11ea-8270-7d3f5df2652a.png)

**Comment by Stevie00911** [comment]
Hello 0312birdzhang,
thank you so much for the manual MTP driver installation description.
I could install it and have now the Vollaphone in my Win10 Explorer as a "Phone" with data folders :-) 
Greetings, Stefan
