### ISSUE TITLE
List of Apps not working 

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#26]
Here are some Apps not working:

- Flas, Internet Radiostation player: does not start, Ubuntu version 16.04. (2020-07-29)
- uNav, Navigation system: does not start, Ubuntu version 16.04. (2020-07-29)

**Comment by Stevie00911** [comment]
- uTorch: Use the LED as a torch: The app opens, but does not switch on the LED, because die app does not show up in der access rights of using the camera, Ubuntu version 16.04. (2020-08-01)

**Comment by wurzer** [comment]
I can reproduce this issue

**Comment by Stevie00911** [comment]
- Axolotl (Signal), Messenger: does not start, Ubuntu version 16.04. (2020-09-06)
- Zombies can't jump, Game: does start, but blank screen, Ubuntu version 16.04. (2020-09-06)
- Youtube, Videoplayer: full screen button not working,

**Comment by JamiKettunen** [comment]
All of these listed apps in here seem to open just fine on `Development` update channel `Ubuntu 16.04 (2020-09-08/2)` build, can you recheck this on that update channel? That should have fixed the launching issues. A few other comments:
- [uNav](https://open-store.io/app/navigator.costales): though this app starts and works, the map UI is very sluggish (not sure if this is a port specific issue)
- [uTorch](https://open-store.io/app/com.ubuntu.developer.majster-pl.utorch): the dev themselves said this is only supported on 5 devices which you can see in the app's own F.A.Q tab as well as before downloading it on the OpenStore page, and also this hasn't been updated in 3 years; besides we could be getting a [flashlight toggle under the "Battery" indicator](https://github.com/ubports/indicator-power/blob/xenial/src/flashlight.c) soon though as @danct12 found out it can be toggled manually from `/sys/class/flashlight_core/flashlight/flashlight_torch` by writing `1` or `0` to it!
- [Zombies can't jump](https://open-store.io/app/zombiescantjump.johandoe1960): the game's not been updated in 3 years and once started just a blank page is visible (with a small menu button on the top right corner which doesn't do anything)
- Youtube: there's many webapps, try [YouTube by Alan Pope](https://open-store.io/app/com.popey.youtube); it has a working fullscreen button as per my testing

**Comment by 0312birdzhang** [comment]
I can confirm **uNav** is woking now, `Ubuntu 16.04 (2020-09-09)` devel channel.

**Comment by Stevie00911** [comment]
Thanks Jami, for the advice to change the update channel from **"edge" to "development"**.
The Vollaphone was delivered with the "edge" channel activated.
On the development channel: **uNav, Axolotl** and **Flas** are working now.
YouTube by Alan Pope is working well with fullscreen.
Thank you and greetings,
Stefan
