### ISSUE TITLE
Phone Radio: talking with the build in micro causes echo effects on the device of the called person

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#27]
Phone Radio: talking with the build in micro causes echo effects on the device of the called person.
The funny thing: when changing the sound to the loudspeaker, the echo effects are gone.
Ubuntu version 16.04. (2020-08-01)

**Comment by JamiKettunen** [comment]
How was the call conducted? I don't seem to get any echo effect even in the same room on the 2 devices after testing (keep in mind the earpiece volume can't seem to be adjusted as per #29, so that might be where the echo is coming from if testing calls on the devices in close proximity!).

**Comment by Stevie00911** [comment]
These are normal inner german calls in the T-Mobile (Deutsche Telekom) net. 
Actually the echo effects are still present, the same behaviour as on August the 3rd.
Ubuntu version 16.04. (2020-09-23) develop

**Comment by Stevie00911** [comment]
Actual situation:
Phone call with the build in micro: loud repetition of the words from the called person on his device.
Phone call with the activated loudspeaker:  silent repetition of the words from the called person on his device.
Ubuntu version 16.04. (2020-10-02) dev

**Comment by JamiKettunen** [comment]
Since output volume during calls can now be adjusted (as of development channel build `2020-10-09/2` as per my testing) can you check whether the echo effect was caused by very loud call volume level?

I'm still unable to reproduce this on 2 different devices in the same room, but I'll see what I can do about testing this in an actual call with someone outside my home.

**Comment by Stevie00911** [comment]
Ubuntu 16.04. release candidate (W43):
Actually the echo effects are still present, the same behaviour as on August the 3rd.
Checked with inner german calls with the T-Mobile (Deutsche Telekom) carrier.

**Comment by Stevie00911** [comment]
Ubuntu 16.04 (2020-W44) release candidate:
The echo effects are still present.

**Comment by Stevie00911** [comment]
Ubuntu 16.04 (2020-W49/2) release candidate:
The echo effects are still present.
My friends and family get more and more annoyed about the still existing echo effects.

**Comment by JamiKettunen** [comment]
As I've not seen anyone else report issues with this (nor have I been able to reproduce this) I suspect it might be a hardware issue, could you try Volla OS on the device and check whether the echo effect still persists?

**Comment by Stevie00911** [comment]
Ubuntu 16.04 (2020-W50) release candidate:
The echo effects are still present.
I use the T-Mobile (Deutsche Telekom) net.
This is curious, is there no other user with this echo behaviour?....

@JamiKettunen: sorry, but this issue is really annoying and present. I do not want to try the Volla OS, because I am afraid to loose all may local data on the Ubuntu touch installation.

With the former BQ Aquaris E5 HD phone I had no echo effects.

**Comment by JamiKettunen** [comment]
Since no one else has reported this I suggest backing up all your data (mostly likely all under `/home/phablet/`) and using the [latest beta version of UBports installer](https://github.com/ubports/ubports-installer/releases/latest) to flash VollaOS just to be sure the echo isn't a hardware related issue, as in that case you should get your device replaced.

**Comment by Stevie00911** [comment]
@JamiKettunen, thank you for your message. 
With the Ubuntu 16.04 (2021-W10) release candidate the echoes are still present.
Trying to flash VollaOS und then reflash to UT ist too much action for me actually.

**Comment by Stevie00911** [comment]
UT OTA 17
Even with OTA 17 the echoes are still present.

**Comment by wurzer** [comment]
Pleasse decrease the loudness to avoid the echo or activate the speaker. Another solution is to use a headset.
