### ISSUE TITLE
Status LED not working

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#28]
In screen off mode no status LED is shown or is blinking if a notification is active, or the battery is charged.
Ubuntu version 16.04. (2020-08-01)

**Comment by JamiKettunen** [comment]
There is no status LED present on the device, this is outlined in the [High level epic overview for Ubuntu Touch port](https://github.com/HelloVolla/ubuntu-touch-beta-tests/wiki/High-level-epic-overview-for-Ubuntu-Touch-port).

**Comment by Stevie00911** [comment]
Ok, thank you for your fast response.
I will close this one.
Greetings, Stefan
