### ISSUE TITLE
Phone Radio: volume buttons do not control the internal loudspeaker while in a call

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#29]
Phone Radio: The volume buttons on the right side of the vollaphone do not control the internal loudspeaker while in a call.
Ubuntu version 16.04. (2020-08-04)

**Comment by wurzer** [comment]
You mean the use case of a call in a hands-free mode?

**Comment by Stevie00911** [comment]
I mean a normal phone call and you type on the loudspeaker symbol (first button on the left) of the phone app.

Additionally the volume buttons on the right side of the vollaphone do not control an attached wired headset. 
The headset with the microphone works well, but no volume control.
Ubuntu version 16.04. (2020-09-06)

**Comment by JamiKettunen** [comment]
As per my testing on `2020-09-14` devel build, the volume output from a call indeed **does not** get adjusted on **any** of the following:
1. Earpiece
2. Integrated loudspeaker
3. Wired headset attached to headphone jack

**Comment by NeoTheThird** [comment]
Potentially an upstream issue: https://github.com/ubports/ubuntu-touch/issues/1402

**Comment by JamiKettunen** [comment]
Volume gets adjusted properly for earpiece, integrated loudspeaker and wired headset on headphone jack during calls as of development channel build `2020-10-09/2`, so closing this issue :)
Please do comment here or create another issue if this still persists after updating!
