### ISSUE TITLE
Time in notification bar is not fully visible.

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#3]
The minutes of the current time is not visible on the screen. A notification bar with greater height would resolve this issue.

**Comment by JamiKettunen** [comment]
For now there is a [temporary fix courtesy of Sander](https://forums.ubports.com/post/44083) which I've made simpler to apply and maintain in [my fork of their vollanotchfix repository](https://github.com/JamiKettunen/vollanotchfix).

**Comment by SanderKlootwijk** [comment]
Great work @JamiKettunen! This makes it a lot easier to apply the fix :)

You should post about this script on the UBports Forum thread!

**Comment by gbdomubpkm** [comment]
Thank you both for this fix !
On the Volla, the Grid Unit of 22 is the right one to be able to see directly the indispensable envelope icon of the notifications as well as the network icon L, 3G  and Time !

**Comment by gbdomubpkm** [comment]
On the Volla, the fix worked with OTA-18. But now i'm on the last RC channel and the fix https://github.com/JamiKettunen/vollanotchfix doesn't seem to  work. Is it possible to apply the notch patch again easily ?

**Comment by gbdomubpkm** [comment]
I don't know why but https://github.com/JamiKettunen/vollanotchfix works again in RC 30 🙂

**Comment by gbdomubpkm** [comment]
https://github.com/JamiKettunen/vollanotchfix doesn't seem to work with OTA-19 currently.

**Comment by gbdomubpkm** [comment]
Works now with OTA-19.

**Comment by gbdomubpkm** [comment]
Hello, i was compelled to reflash OTA-20 my volla with wipe option and https://github.com/JamiKettunen/unity8-notch-hax doesn't work currently.
![screenshot20211207_084640298](https://user-images.githubusercontent.com/50362604/144988724-158014c2-f032-4417-8a18-5b6b36832d5b.png)
Impossible to find the patch package

why the patch works intermittently? why the patch is not included in the different dev rc stable channels?

**Comment by wurzer** [comment]
See ticket #112
