### ISSUE TITLE
Frequent restarts of the device during a day

### ISSUE THREAD

**Issue by wurzer** [HelloVolla/ubuntu-touch-beta-tests#31]
A beta tester reports:

> Sometimes it doesn't occur and other moments on a day its rapidly after each other. Also things that I don't get. When I downloaded a online map from the NL, DE, or BE it gives no problem on my old FP2 but I didn't succeeded on Volla because its restarts while downloading. I tried at least >15 times

**Comment by UniversalSuperBox** [comment]
Does this user still report this problem on newer versions of Ubuntu Touch? Could we get a better overview of the apps and websites running on their device when the crashes occur?

**Comment by gbdomubpkm** [comment]
@wurzer Is this bug reproducible? I could never confirm it.

**Comment by wurzer** [comment]
Not at all

**Comment by gbdomubpkm** [comment]
> Not at all

What do you mean ? that it is not reproducible but still happens from time to time, or that you no longer have it at all ? 🙂

**Comment by wurzer** [comment]
I can't reproduce frequent reboots of the device, neither on Volla Phone nor on VollaPhone X.

**Comment by JamiKettunen** [comment]
I'll close this issue since it hasn't been observed by anyone for a long time, this issue can be re-opened or a new one created if this still occurs.
