### ISSUE TITLE
Opening a message (SMS) directly from the notification menu the keyboard is missing

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#34]
Opening a message (SMS) directly from the notification menu the keyboard does not appear.
You have to restart the message app to receive back the keybord for typing an answer.
Ubuntu version 16.04. (2020-08-11)

**Comment by wurzer** [comment]
I can't reproduce this issue

**Comment by Stevie00911** [comment]
Still an issue on my vollaphone
Ubuntu version 16.04. (2020-09-06)

**Comment by JamiKettunen** [comment]
Cannot reproduce on `Development` update channel build `2020-09-11/3` even when tapping the notification on the lockscreen. Could you check if this is still an issue for you @Stevie00911?

**Comment by JamiKettunen** [comment]
I still cannot repro this on `devel` channel build `2020-09-23` as per the steps in my previous comment, closing this as there's been no response for nearly 2 weeks.
Please open another issue if you're still experiencing this and include your update channel name as well. Thanks :)

**Comment by Stevie00911** [comment]
Yes, with the actual "devel" channel build the keybord appears now. :-)
Ubuntu version 16.04 (2020-09-22) "devel"
