### ISSUE TITLE
When opening m4v in media player the loudspeaker is not used by default, making audio hard to hear.

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#35]
When opening m4v in media player the loudspeaker is not used by default, making audio hard to hear.

**Comment by wurzer** [comment]
I can't reproduce this issue. Maybe you can provide an example file.

**Comment by mokmeister** [comment]
Issue has been resolved.

**Comment by mokmeister** [comment]
Issue has been resolved.
