### ISSUE TITLE
Carrier registeration lost during boot

### ISSUE THREAD

**Issue by TellingBerto** [HelloVolla/ubuntu-touch-beta-tests#39]
To whom it may concern.

I encounter this strange behavior with Phone: VollaPhone (OS: 2020-09-04)

Steps processed:

    Boot smartphone.
1. Enter SIM 1 - pin.
2. Registration with phone provider takes place successfully, network icon is ACTIVE.
3. Wait a some seconds, network icon is getting INACTIVE.
4. Enter pin for the device.
5. Network icon remains INACTIVE.
6. Checking in network settings.
       SIM 1 is shown as "Unregistered", carrier is available (automatically pulled).

Turning flight mode on/off did not help and multiple reboots did not change the behavior. 

Even this procedure did not help:

1. Boot smartphone.
2. Do not enter pin of SIM 1.
3. Enter pin for the device.
4. Open network from icon bar and choose "Unlock SIM" .
5. Enter pin for SIM 1.
6. If the icon is not getting activated:
7. Activate flight mode and deactivate flight mode.
Carrier: Deutsche Telekom

**Comment by wurzer** [comment]
Do you mean access to the cellular network for calls and short messages or the cellular network for data traffic? Did you check the APN settings? If they are empty, you can try to set them manually.

**Comment by TellingBerto** [comment]
Access to the cellular network for calls and short messages is constantly lost during boot.

Verified again (12.09.2020):
1. Enter SIM 1 - pin.
2. Registration with phone provider takes place successfully, network icon is ACTIVE.
3. Wait a some seconds, network icon is getting INACTIVE.
4. Enter pin for the device.
5. Network icon remains INACTIVE.
6. Checking in network settings.
7. SIM 1 is shown as "Unregistered", carrier information is not available.
8. Try to set it manually -> turning cycle displayed -> "Automatically" flagged as default
9. "26202" (Dt. Telekom) displayed but could not be chosen.

Result: No registration, no calls, no SMS, no data via cellular network.

Current OS-Version: 2020-09-12/2
Chanel: Developer

**Comment by TellingBerto** [comment]
While discussing the other issue with failure of roaming and usage of the phone abroad I noticed some strange behavior which might be helpful to find the underlying problem.
Everything I mentioned is still valid.

When power off the phone yesterday I had a cellular connection. 
Today I started the phone again and was able to establish a cellular connection and use cellular data, e.g. was able to check the mails. (This was quite surprising to me because I faced very often a failure here during the last couple of days.)

I made a change in the settings for time/date to manually and changed the current time to a different one (-2 hours) and powered off the device. 
After reboot I was not able to establish a cellular connection again. Situation persists even after changing the time back to current time and switching back to automatically. Proven by multiple reboots with with the settings (manual/wrong time; manual/correct time; automatically).
The only solution I´m aware of to be able to get the cellular connection back to work is:
1. Activate Wi-Fi (to synchronize the time) 
2. Power off & reboot
3. Enter SIM pin (and pray)
Result: Cellular connection was established successfully (again).

So I think issue is partly caused by the time synchronization and thus also affect the international roaming, issue #45. 
Hope this helps to identify and fix the issue(s).

**Comment by TellingBerto** [comment]
Additional different behavior w. r. t. carrier registration in case the user shut down the mobile phone with_
"Power off" vs. "Restart".

If "restart" is chosen no successful carrier registration takes place with the next boot, even when the phone had a working cellular connection before.

OS build: 2020-09-14

**Comment by JamiKettunen** [comment]
Could this be yet another instance of #55? I've not been able to reproduce this myself on latest current Development channel build.

**Comment by TellingBerto** [comment]
Ubuntu version: 2020-10-13/2
Channel: dev

Issue can be closed. No failure detected anymore.
Many thanks for solving this issue.
