### ISSUE TITLE
Updates in mir-android-platform brakes some thing

### ISSUE THREAD

**Issue by luka177** [HelloVolla/ubuntu-touch-beta-tests#40]
- Libertien

-  mirscreencast

- sdl apps

Always same error:
```
hybris_gralloc_retain:244: called gralloc method without gralloc loaded
mirscreencast: gralloc.c:244: hybris_gralloc_retain: Assertion `NULL' failed.
```
Related to : no idea, mb https://github.com/ubports/mir-android-platform/commit/4d3fa8ad0883f2b6340f32f3c6c9e04706320e3a

**Comment by luka177** [comment]
https://paste.ubuntu.com/p/GQ2k5hXmCv/ strace of Xmir

**Comment by NeoTheThird** [comment]
cc @notkit

**Comment by luka177** [comment]
It is related to lack of glamor initialize functions, i want able to fix it sadly (got it to work with simple sdl app)

**Comment by wurzer** [comment]
Still valid ticket?
