### ISSUE TITLE
Cannot send file to Phone via MTP on Windows 10

### ISSUE THREAD

**Issue by 0312birdzhang** [HelloVolla/ubuntu-touch-beta-tests#43]
Select the file, right click, send to `Phone`, nothing happening, but manually copy/paste works.

Ubuntu 16.04 (2020-09-09)

**Comment by NeoTheThird** [comment]
You can only send it to the subfolders, that works on windows 10 as well. Would you mind trying again?

**Comment by 0312birdzhang** [comment]
> You can only send it to the subfolders, that works on windows 10 as well. Would you mind trying again?

Yes, it works.

**Comment by NeoTheThird** [comment]
Then we can close this, right?
