### ISSUE TITLE
Cellular data roaming (abroad) not possible

### ISSUE THREAD

**Issue by TellingBerto** [HelloVolla/ubuntu-touch-beta-tests#45]
While moving from country1 (with carrier1) to country2 (with carrier2) the origin carrier (carrier1) from country1 is still displayed as carrier with the result of no SMS, calls nor data. 

I assume the step "user profile loaded into data base of carrier2" called VLR (Visitor Location Register) has been processed successfully. Because I received 2 SMS. One with Covid-19 information from Switzerland and one from my German provider with cost information of calls abroad.

The name of carrier2 (which would be Swisscom in my case) is not written next to the network bar and a small triangle.
Just noticed the name of carrier2 next to the network bar after I made several reboots.

Same technical behavior between German and French carriers. 

OS-Version: 2020-09-12/2
Channel: Developer

**Comment by TellingBerto** [comment]
Update: 01.10.2020
OS-Version: 2020-09-29/2
Channel: Developer

When phone is rebooted abroad registration is working at carrier2, roaming symbol is displayed.
Receiving a call & placing a call is possible.
Receiving SMS & sending SMS is possible.

Data connection is not possible (with roaming for data active).

**Comment by JamiKettunen** [comment]
If at all possible, could you re-test this? It could be yet another instance of #55 and similar telephony issues.

**Comment by TellingBerto** [comment]
Retest.

OS-Version: 2020-10-13/2
Channel: Developer

Issue partly fixed.
Working: 
Registration is transferred from carrier1(coutry1) to carrier2(country2) automatically. 
Receiving a call & placing a call is possible.
Receiving SMS & sending SMS is possible.
Roaming indicator is displayed. No reboot necessary.

Not working: 
Cellular data not working (when roaming for cellular data is active).  
Cellular data indicator is displayed.

**Comment by UniversalSuperBox** [comment]
Hi @TellingBerto, I think the issue with mobile data while roaming is actually related to https://github.com/ubports/ubuntu-touch/issues/1657, and this issue could be closed. But before that, on which carrier were you failing to use mobile data and on which carrier was it working?

**Comment by wurzer** [comment]
Ut should be fixed with OTA 16
