### ISSUE TITLE
SUGGESTION - Improved Fingerprint Reader User Dialogue

### ISSUE THREAD

**Issue by wayneoutthere** [HelloVolla/ubuntu-touch-beta-tests#46]
Amazing device! Great work everyone, indeed!

One super cool feature I just discovered was the fingerprint reader.  However, to maximize the popularity of it and be able to create more buzz about it, I think the user experience during setup needs to be improved.  I will present my ideas here, and, of course, they can be edited, condensed, etc, etc.  

My experienced was, until I figured out how it worked and how to set it up, that it was a big frustrating and it didn't work reliably until I figured out (by guessing) how it worked.

## Suggestion 1 - Add 'intro and welcome' page before the swipe page.
Before the 'swipe your finger over the reader' screen, something like this:

Intro blurb:

**Fingerprint Registration for Unlocking your Ubuntu Touch Device** 

The fingerprint reader used to unlock your device does not store your fingerprint on any server or any database.  You can unlock knowing that only those fingerprints you authorize can unlock this device and they stay safe on your device only.

You can set up multiple fingerprints and this may be beneficial if you plan to use both hands, use the phone in different positions (ie. in landscape orientation), or if you plan to give authority to someone else to unlock your device.  Just enter back into this setup section and select 'add fingerprint' again to register different 'variations' of your fingerprint or other fingerprints.

When registering your fingerprint, be sure to hold the device in a natural way - the way you plan to hold it when unlocking.  This will help the fingerprint reader function reliably each time and improve your experience.

Let's get started...

![Volla_ut_fingerprint_reader_01](https://user-images.githubusercontent.com/16578346/93607170-d485fb00-f97d-11ea-9478-87f2c9a5379b.jpg)

For this screen above, I would suggest something like this:

**First, swipe your finger over the reader to begin the process.**

![Volla_ut_fingerprint_reader_02](https://user-images.githubusercontent.com/16578346/93607283-f97a6e00-f97d-11ea-844a-710d7be28b66.jpg)

For this screen, I would suggest something like this:

**Next, tap your finger repeatedly on the reader.  As a guideline, use reasonable pressure while holding down your finger long enough to allow the reader to properly function.  Consider how long you press a touch screen and add a little more time.  You may change the duration of your taps, but keep in mind these guidelines to assist the reader and improve your experience.**

**Comment by wayneoutthere** [comment]
Additional suggestion: quick 'how to guide' on last page:

# Before using your new fingerprint reader

Now that you have successfully registered your fingerprint with your device, take a moment to note how to use it.

From sleeping mode, tap the fingerprint reader one to 'awaken' the device.
Then, simply apply your finger to the reader in the same way and position that you trained your device above.  Sometimes this step requires a slightly longer push to unlock the device. 
That's it!

Should you have an issue with the fingerprint improperly reading, simply unlock the device manually with your passcode, and re-register your fingerprint(s) following the steps you just performed.

**Comment by mariogrip** [comment]
I would suggest maybe moving this to ubports tracker? as this is not a volla phone specific bug/suggestion?

**Comment by JamiKettunen** [comment]
I'll close this as it isn't something device specific and as Marius stated above, is better suited to the general [UBports bug tracker](https://github.com/ubports/ubuntu-touch/issues) :)
