### ISSUE TITLE
Can't fast charge Volla (charge while off)

### ISSUE THREAD

**Issue by wayneoutthere** [HelloVolla/ubuntu-touch-beta-tests#48]
I had a short time to charge my device while near plug.  
I turned the device off in hopes of charging as much as possible in the shortest time.
Every time I inserted the USB charger, the device turned on and would not stay off.

* Tried to power off first, then plug in - fail
* Tried to turn on, then power off with software, while plugged in - fail
* Tried to hard reset holding power button for 10s - fail

**Comment by NeoTheThird** [comment]
This is probably #37?

**Comment by JamiKettunen** [comment]
This will be fixed when the issue Jan mentioned is fixed, so I'll go ahead and close this one as a duplicate :)
