### ISSUE TITLE
Sound is distorted

### ISSUE THREAD

**Issue by rubencarneiro** [HelloVolla/ubuntu-touch-beta-tests#49]
If the device volume is on max you will hear cracking sound when playing music ou youtube videos etc.
It also happens when sound is low.
I can confim is halium port issue since it doesnt happens on volla firmware.

**Comment by Mattia990** [comment]
I confirm it.
This problem happen also to me when the volume is at minimum "power".

**Comment by JamiKettunen** [comment]
Probably related to if not the same issue as #33

**Comment by mariogrip** [comment]
Same as https://github.com/HelloVolla/ubuntu-touch-beta-tests/issues/33
