### ISSUE TITLE
Cannot enable speaker phone while in a call

### ISSUE THREAD

**Issue by mokmeister** [HelloVolla/ubuntu-touch-beta-tests#5]
Initiate a call as the calling party. When in the call, hitting the speaker phone indicator enables the indicator but does not change the audio to speaker phone, ie. you still have to hole the phone to your head to hear the audio of the called party.

**Comment by wurzer** [comment]
Known issue for the first call.

**Comment by Stevie00911** [comment]
See issue #27, on my vollaphone I can switch to the speaker while in a call.
Ubuntu version 16.04. (2020-08-11)

**Comment by JamiKettunen** [comment]
Toggling between loudspeaker/earpiece audio in calls works perfectly fine on `Development` update channel `Ubuntu 16.04 (2020-09-08/2)` build; this issue can be closed.
