### ISSUE TITLE
 Again: Opening a new message (SMS) directly from the notification menu the keyboard is missing

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#52]
This Issue is back again:
Opening a new message (SMS) directly from the notification menu the keyboard in the message app does not appear.
You have to restart the message app to receive back the keybord for typing an answer.
Ubuntu version 16.04. (2020-10-02) dev

**Comment by JamiKettunen** [comment]
This is definitely [an upstream issue](https://github.com/ubports/ubuntu-touch/issues/1444) and nothing specific to the Volla Phone port (which is what the issues here are meant for).

**Comment by Stevie00911** [comment]
Ok, so should this issue be closed here?
