### ISSUE TITLE
Sideways Photo View after Taking Photo

### ISSUE THREAD

**Issue by wayneoutthere** [HelloVolla/ubuntu-touch-beta-tests#54]
I was trying to file this bug a long time ago but it is not possible to actually screenshot this screen (another bug? UT bug?).  So I had to find a second device to take a picture.

I assume this is a Volla bug because I have not experienced this in any other UT device and I have N5, FP2, N4, etc.

## What I expected
* Take a picture
* Swipe left to review picture
* See picture in correct / same orientation as when I took the picture

## What is happening
* Take picture
* Swipe left to review
* See picture rotated 90 degrees counter-clockwise

The following picture was taken with the cartoon in regular vertical view, and as you can see in the 'review mode' it is rotated 90 degrees to the left (I did not do that - happened automatically)

![ut_volla_sideways_photo_01](https://user-images.githubusercontent.com/16578346/94991517-8efa2e00-0538-11eb-9ff9-bd012fb91a1b.jpg)

**Comment by wurzer** [comment]
Currently you can only take photos in the landscape mode. The rotation sensor is working, but it's not considered by the cam app for photos. It works only for videos. We will work on this.

**Comment by JamiKettunen** [comment]
Taken photos are now rotated correctly as of development channel build `2020-10-08/2`, so closing this issue :)
Please do comment here or create another issue if this still persists after updating!

**Comment by wayneoutthere** [comment]
awesome! working for me now after update. Thanks much!
