### ISSUE TITLE
Screen unlocking should be possible with more/all options together

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#56]
There are 4 options to choose for unlocking the screen:
- fingerswipe (no security)
- Pin with 4 digits
- Password
- Fingerprint

The problem is, that you can choose only one option and not more or all together.

I just learned successfully a fingerprint with the phone, but I hesitated to choose this for unlooking the scrren.
What will happen, if the finger is not recognized and the phone does not unlock the screen anymore?
You can only reset the phone?
The android phone of my son has the possibility to choose more or all options for unlocking the screen.
So, if the fingerprint recognition fails, he can type his pin code for example.
For me, this is more secure and I miss this on the vollaphone, too.

Ubuntu touch version 16.04. (2020-10-05)

**Comment by Mattia990** [comment]
You can use fingerprint unlock with the password.

**Comment by wurzer** [comment]
This is not a Ubuntu Touch porting issue.
