### ISSUE TITLE
Notifications - wrong date/time for new SMS

### ISSUE THREAD

**Issue by TellingBerto** [HelloVolla/ubuntu-touch-beta-tests#59]
Hello,
to whom it may concern. 

When receiving a new SMS the indicator (envelope) for notifications is getting green in the indicator bar. 
This is how it should work.
When opening the "envelope" the user is getting a list of the new SMS, like expected.

**Issue:** 
Date/time information is not correct for SMS related entries. Date is set in general to: "Thu, 1. Jan 1:00 am".

When receiving a mail the date/time information is fine in the notification list.

Cross check with device "BQ E5 HD", were able to verify this issue is only on UT for VollaPhone.

**Comment by TellingBerto** [comment]
FYI:

To whom it may concern: 
Developer follow up: https://github.com/ubports/telepathy-ofono/pull/17

**Comment by JeroenBots** [comment]
![image](https://user-images.githubusercontent.com/21966556/99306709-d3762a80-2855-11eb-92aa-fe78fda32964.png)

**Comment by peat-psuwit** [comment]
https://github.com/ubports/telepathy-ofono/pull/19 is now merged. Please wait until the next devel image and then please check if the issue is fixed.

**Comment by TellingBerto** [comment]
**Retest**

**Result:** 
Issue fixed with UT 2020-11-27/2.

Many thanks for sorting out the issue.
