### ISSUE TITLE
Fingerprint recognition and screen unlocking misbehaviour

### ISSUE THREAD

**Issue by Stevie00911** [HelloVolla/ubuntu-touch-beta-tests#62]
The fingerprint recognition stopps at 93% and can only be aborded, but a fingerprint is saved.
After a reboot the unlocking screen does not recognize the fingerprint anymore and only password unlocking is possible.
The unlocking option "Fingerprint" is greyed out and cannot be choosen anymore. 
The recorded fingerprints are still present.

By the way, I suggest to add an unlocking option with "Pin and fingerprint".

Ubuntu 16.04 (2020-W43) release candidate

**Comment by JamiKettunen** [comment]
There was a regression on initramfs level which has now been resolved, and fingerprint stuff is working perfectly fine as of development channel update `2020-10-30/2` and I think a similar patch was also pushed to RC channel.
Please retest this and close the issue/comment back as needed!

> By the way, I suggest to add an unlocking option with "Pin and fingerprint".

We aren't developers of the dialog, I suggest bringing this up in [the general UBports bug tracker](https://github.com/ubports/ubuntu-touch/issues) :)

**Comment by JamiKettunen** [comment]
As this still works on my installed `2020-11-06` development channel build after a week of testing previously and the RC channel has thus received at least one update, I'll go ahead and close this issue.

Please comment or make another issue if it still persists after upgrading! :)

**Comment by Stevie00911** [comment]
Well done Jami, thank you so much.
Fingerprint recording works and screen unlocking works, but no always.
Sometimes the fingerprint unlocking is not recognized and I have to unlock the screen via password. 
I have the impression, this occures after the phone is not used for a longer period.
Ubuntu 16.04 (2020-W44) release candidate
