### ISSUE TITLE
Battery charging icon  - different behavior

### ISSUE THREAD

**Issue by TellingBerto** [HelloVolla/ubuntu-touch-beta-tests#63]
Hello,

when phone is plugged to USB cable we have 2 different behavior w.r.t. the battery icon (not the process to charge the phone as such, this is working):

1. USB-cable plugged in to charger: The battery icon is green in the notification hub, indicating the phone is currently being charged.

2. USB-cable plugged in to PC: The battery icon remains white in the notification hub, not indicating the phone is currently being charged, but technically it is.

**Comment by JamiKettunen** [comment]
On a low (maybe less than 25%?) this also prevent upgrading the OS even if the phone is plugged in via USB to a computer for example; I'm looking into a fix for this.
