### ISSUE TITLE
Phone number of incomming call is not resolved in the notification list.

### ISSUE THREAD

**Issue by TellingBerto** [HelloVolla/ubuntu-touch-beta-tests#66]
Hello,

for incomming calls the phone number is not resolved in the notification list.

Steps processed:
1. Maintain contact in contact app with name and phone number [fixed line or mobile] (international format) .
2. Receive a call from the number created in step #1, don´t pick up the call.
3. Check enties in notification.

**Result:** Incomming call added as new entry, but number not resolved.

![image](https://user-images.githubusercontent.com/61089736/98440767-e6bd2380-20fa-11eb-9cb7-4f0ce407a2cd.png)

UT: 2020-11-06, channel: DEV

**Comment by JamiKettunen** [comment]
Can confirm, the phone number is always shown instead of a saved name even if it's in the non-international format.
