### ISSUE TITLE
Use of issue templates

### ISSUE THREAD

**Issue by Flohack74** [HelloVolla/ubuntu-touch-beta-tests#68]
Would be great if we start using issue templates similar to that one:

**Details about installed OS version**

Info about which OTA/Image you are reporting this issue for.

**Describe the bug**

**To Reproduce the bug**

Description should look similar to this:

2. Scroll down to '....'
3. Click on '....'

**Expected behavior**

**Screenshots**

If applicable, add screenshots to better explain your problem.

**Additional context**

**Comment by luka177** [comment]
+1
