### ISSUE TITLE
Front Camera Pictures are in wrong rotation

### ISSUE THREAD

**Issue by McMarius11** [HelloVolla/ubuntu-touch-beta-tests#72]
Would be great if we start using issue templates similar to that one:

Details about installed OS version

Info about which OTA/Image you are reporting this issue for.

Describe the bug

To Reproduce the bug

Description should look similar to this:

go to 'camera'
change to front camera
take a horizontal picture
look at the photo in gallery
see that it's in the wrong rotation.

Expected behavior

See that's in the right rotation

**Comment by peat-psuwit** [comment]
Please check if the issue persists in the latest devel channel image.

**Comment by JamiKettunen** [comment]
I just tested this on devel image `2020-11-26/2` and this seems to be fixed along with front camera recordings previously causing the app to freeze! :+1:

**Comment by JamiKettunen** [comment]
I'll go ahead and close this issue now as I already tested this as working on the latest Development channel build yesterday; if the issue still persists after updating feel free to open a new one! :)
