### ISSUE TITLE
Connecting Volla Phone with to Ubuntu PC via USB not working

### ISSUE THREAD

**Issue by steffi-hh** [HelloVolla/ubuntu-touch-beta-tests#76]
Connecting Volla Phone with Ubuntu 16.04 (OTA-14) to a PC with Ubuntu 18.04.5 LTS.
Screen of Volla Phone is unlocked.
On PC: Try to open Volla Phone device like an USB stick (click on the small stick icon and then "open with file browser").
Then the error occures:
The file or folder udi=/org/kde/solid/udev/sys/devices/pci0000:00/0000:00:14.0/usb1/1-2/ not exists.

**Comment by JamiKettunen** [comment]
I can't reproduce this on the latest Development channel build; could you try another file manager (such as `nautilus` or `nemo`)? I've personally had a really bad experience regarding MTP file transfers and any KDE programs using KIO as the backend.

**Comment by steffi-hh** [comment]
Great thank you! It is working with nautilus.
