### ISSUE TITLE
Truncated time display

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/ubuntu-touch-beta-tests#78]
**Details about installed OS version**
Seen with RC 2020-W49/2 but on each channel ?

**Describe the bug**

Due to the curved angles of the display, the time in the upper right-hand corner is truncated.
The central notch also truncates the indicators aligned with this notch.

**Expected behavior**
See each indicator on the indicator bar in its entirety and especially the time..

**Screenshots**
![image20201204_224923834](https://user-images.githubusercontent.com/50362604/101220704-6c92a700-3686-11eb-8ea9-05855011a822.jpg)

**Comment by MarkMuth** [comment]
This is discussed over at #ubports/ubuntu-touch#523 and related to #3.

**Comment by JamiKettunen** [comment]
Thanks for the screenshot, however issue has been reported in this bugtracker before and linked by Mark above, so I'll close this one.
