### ISSUE TITLE
Wrong Date and Time After Reboot

### ISSUE THREAD

**Issue by MarkMuth** [HelloVolla/ubuntu-touch-beta-tests#79]
Sometimes after a reboot the phone shows a date and time in October 2031, which will only be corrected after several hours of waiting. This is especially bad as HTTPS certificates are regarded as expired and users are warned about insecure connections.
![WrongDate](https://user-images.githubusercontent.com/4218151/101222437-0dcf2c80-368a-11eb-9b64-1f31ad68507d.png)

**Comment by JamiKettunen** [comment]
This is really odd, could you upload a copy of your `/var/log/syslog` somewhere (e.g. paste service) when this happens after booting? I've never seen this on my unit during development work.

**Comment by JamiKettunen** [comment]
As I've not been able to reproduce the issue and haven't heard back from you for three months I'll go ahead and close the issue. If you're still experiencing this issue, please comment or create another issue with some additional information! :)
