### ISSUE TITLE
Update animation wonky

### ISSUE THREAD

**Issue by NeoTheThird** [HelloVolla/ubuntu-touch-beta-tests#8]
The Update animation in recovery is imperfect. The entire background should be gray and the blinking animation should be a little lower and smoother. Might be due to the animation being implemented on a fairly low level and tied to cpu cycles, making it weird on a fast cpu.

**Comment by mariogrip** [comment]
*should* be fixed by https://github.com/ubports/halium_bootable_recovery/pull/3
