### ISSUE TITLE
State of Anbox

### ISSUE THREAD

**Issue by witty91** [HelloVolla/ubuntu-touch-beta-tests#83]
In the Wiki Anbox is listed as installable. Is there any additional information available?

**Comment by JamiKettunen** [comment]
I suppose [Vince's OnePlus 2 Anbox instructions](https://gist.github.com/Vince1171/69cdcb2e90f2c70e3ee24de93da8caac) would be usable, but it's not really official and also doesn't work super well currently. Feel free to use them if you want to play around though!

**Comment by witty91** [comment]
Thank you for the incredibly quick response! I'll give it a try in the next couple of days.

**Comment by witty91** [comment]
Hi there, 
I would like to give a quick update on this here. At my second attempt of following the OnePlus 2 instructions mentioned above, I actually managed to get the container running and start most of the default apps that come with it. Installing additional Apps using adb install also works, currently I have F-Droid running on the device! I have to say I am quite impressed with this as it runs really smooth :-)

**Comment by JamiKettunen** [comment]
I'll go ahead and close this as it wasn't necessarily a bug report / feature request :)
