### ISSUE TITLE
[request] Increase the font size of the Volla's special action menus

### ISSUE THREAD

**Issue by gbdomubpkm** [HelloVolla/ubuntu-touch-beta-tests#84]
Yesterday I reflashed a Volla smartphone with the installer. The information appearing in relation to the flashing on the Volla  screen is written in an extremely small, almost illegible font : it's very hard to know what we are doing.

   For example, Ubports recovery menu, OEM warning page unlock the bootloader...

   Would it be possible to increase the default font size of these pages ?

**Comment by wurzer** [comment]
Font size can be modified with UT Tweak Tools from App Store
