### ISSUE TITLE
Statistics of the daily usage not displayed on the welcome screen

### ISSUE THREAD

**Issue by stanwood77** [HelloVolla/ubuntu-touch-beta-tests#85]
### Details about installed OS version:  

UBports - Ubuntu 16.04 / OTA-15 Stable

### Bug description:

Welcome screen does not show the daily statistics of usage, although the option is well activated in the security settings.
This bug is a minor issue and has been already confirmed by another user.

See attached screenshot

Occurrence: All the time

Many thanks for your attention.

Steve

![Volla Homescreen](https://user-images.githubusercontent.com/62994815/103177396-86d13680-487a-11eb-87f9-5507990a4011.jpg)

**Comment by gbdomubpkm** [comment]
this is an issue for all halium 9 devices : https://github.com/ubports/ubuntu-touch/issues/1624

**Comment by Flohack74** [comment]
The underlying issue is being fixed, but the problem is that it will only be visible after a factory reset. We are still working on a migration scenario for devices that have been initialized before the fix and now carry a wrong permission id on a folder. It will probably be a small startup job for the user...

**Comment by gbdomubpkm** [comment]
After doing a clean reinstall (with Wipe option in the installer) and testing, I just realized that it seems fixed on OTA-20.
![screenshot20211219_023043836](https://user-images.githubusercontent.com/50362604/146660620-f634144c-e239-4111-be20-c6d8d53c52eb.png)

**Comment by Flohack74** [comment]
Well its fixed when you wipe. I will try to make a migration job into OTA-21 to also fix it for existing users that do not want to wipe :)

**Comment by gbdomubpkm** [comment]
Yes.
... and i moved to RC 42  and it remained fixed 🙂

**Comment by gbdomubpkm** [comment]
Isn't it fully fixed ? If yes, it can be closed.

**Comment by stanwood77** [comment]
Issue is fixed. I close the issue
