### ISSUE TITLE
Fingerprint not working after using developer mode

### ISSUE THREAD

**Issue by jojumaxx** [HelloVolla/ubuntu-touch-beta-tests#90]
**Details about installed OS version**
Ubuntu Touch 16.04 OTA-15 stable

**Describe the bug**
On the screen where you activate the developer mode is also the "Sicherheit nach dem Sperren" (security after lock) option. The text above says: "Sie benötigen eine PIN oder eine Passphrase, um den Entwicklermodus zu benutzen." (You need a PIN or a passphrase in order to use the developer mode). That implicated (to me) NO fingerprint. So I set a PIN there and used the developer mode.  
After that the fingerprint function was completely gone. I couldn't unlock the phone anymore using the fingerprint function. No reaction at all. In the settings ("Sicherheit und Datenschutz"/"Security and data protection" -> "Sperren und Entsperren"/"lock and unlock") I checked for the fingerprint function. It was deactivated "Sicherheit nach dem Sperren" (security after lock) and couldn't be activated (greyed out) although my fingerprint-ids where there.

**Workaround**
After some trial and error I deleted all my fingerprints and created new ones. After that, the fingerprint option wasn't deactivated (greyed out) any more and could be chosen again.
It seems like the phone "forgot" about the fingerprints that have been saved at that time when I set that PIN. Then I couldn't choose the fingerprint option, since "there were" no fingerprints.

**Steps to reproduce the bug**
(The following is an example:)
1. Go to 'settings' -> 'Info' -> 'Developer mode'
2. Go to 'Security after lock' ('Sicherheit nach dem Sperren')
3. Set a PIN
4. Activate and deactivate 'developer mode' (not sure, if that step is even necessary)
5. Lock phone and try to unlock with fingerprint sensor

**Expected behavior**
Nothing. Unlock only via PIN possible

**Screenshots**
Can hardly be screenshotted

**Additional context**
Maybe the same behaviour appears when setting a PIN in the settings ("Sicherheit und Datenschutz"/"Security and data protection" -> "Sperren und Entsperren"/"lock and unlock") which appears to be the same menu and maybe accesses the same code (didn't check that).

**Comment by JamiKettunen** [comment]
I'll have to test on my OnePlus 5, but I'm pretty sure this is an upstream `biometryd` issue present on all (Halium 9?) devices.

**Comment by Stevie00911** [comment]
Same behaviour on my vollaphone in developper mode. 
The system forgets the fingerprints after a time and only password unlocking is poosible.

On th release candidate (2020-W50) the fingerprints stay saved in the system.
But the fingerprint unlocking works not always.
After a reboot and often after a while only password unlocking is possible.
So even under the release candidate the fingerprint unlocking is not working well.

**Comment by JamiKettunen** [comment]
I couldn't reproduce this issue on my Volla Phone running dev channel `16.04 (2022-07-08)` build. Regarding your problems with the unlocking this mostly seems to be #99, and for the rest of your problems I've made issues upstream:
- [Unlocking: Make it clear passcode/passphrase is needed after reboot when using fingerprint](https://gitlab.com/ubports/development/core/lomiri/-/issues/24)
- [Developer Mode: Hide "Lock security" section entirely if something other than "Swipe (no security)" is already chosen](https://gitlab.com/ubports/development/core/lomiri-system-settings/-/issues/313)

Please re-open this or create a new issue if your saved fingerprints still are becoming unusable (following the steps outlined here) on the latest Ubuntu Touch version!
