### ISSUE TITLE
Cellular data doesn't work on SIM 2

### ISSUE THREAD

**Issue by JamiKettunen** [HelloVolla/ubuntu-touch-beta-tests#93]
**Details about installed OS version**
Applies to all current Ubuntu Touch builds for the Volla Phone.

**Describe the bug**
Cellular data doesn't work on SIM 2 while other cellular functions do.

**Steps to reproduce the bug**
1. Attempt switching data to the second inserted SIM
2. Connection to cellular data doesn't work

**Expected behavior**
Cellular data is switched to the second SIM card and the data connection works.

**Comment by gbdomubpkm** [comment]
I tried to put ONLY a sim card in slot 2 and i confirm that doesn't work : said sim 2 'unknown', wheareas it say 'no sim' for slot 1 which is exact.

**Comment by JamiKettunen** [comment]
This should be partially solved on OTA-16; you can now select the data SIM to use, **but** this setting cannot be read back properly during boot yet so you'll have to choose the data SIM again after rebooting.

**Comment by mateosalta** [comment]
oh, I actually thought I broke my tray. good to see it is a bug :)

**Comment by natur-produkt** [comment]
I fixed this bug in OTA-16, however, sometimes activation of second SIM data fails. Has anybody encountered that?

**Comment by gbdomubpkm** [comment]
What is the status of this bug in OTA 17 or in RC 20 ?
Is it fully solved ?
I haven't two sim to test currently.

**Comment by wurzer** [comment]
This should now be solved with OTA-18. The only remaining issue is, that can only send and receive MMS with the SIM card, that you have selected for mobile data access.
