### ISSUE TITLE
Unable to fromat SDcard

### ISSUE THREAD

**Issue by rubencarneiro** [HelloVolla/ubuntu-touch-beta-tests#97]
OTA-16

BUG:
Unable to format sdcard the screen just stays the same wont umount does nothing,

Try to format sd card

**Expected behavior**
Format sucessful or umount

**Comment by wurzer** [comment]
Which size does the SD card have?

**Comment by rubencarneiro** [comment]
32 gb

A domingo, 23/05/2021, 23:06, Dr. Jörg Wurzer ***@***.***>
escreveu:

**Comment by gbdomubpkm** [comment]
In fact, the memory card manager doesn't seem to work in its entirety since I can't seem to unmount the SD card (named SDU1, doesn't have the name I gave it) : frozen 'remove safely' button.

**Comment by Flohack74** [comment]
This should be fixed with https://gitlab.com/ubports/core/ciborium/-/merge_requests/4 now, please re-test. Also, exFAT format should be now supported, see https://gitlab.com/ubports/core/ciborium/-/merge_requests/2

**Comment by Flohack74** [comment]
Please close that, the issue has been fixed...
