### ISSUE TITLE
mtp-server error

### ISSUE THREAD

**Issue by rubencarneiro** [HelloVolla/ubuntu-touch-beta-tests#98]
Ubuntu 16.04 OTA-16

Unable to use mtp on music plauer to push musics into device.
Device wont appear

1. Just open music player on desktop ( rythmbox)
2. Unable to fimd device

Device should appear as phone
http://paste.ubuntu.com/p/MJnHF8y7Hk/

**Screenshots**
(If applicable, add screenshots here to better explain your problem.)

**Additional context**
(If applicable, add any other context about the problem here, such as log file attachments.)

**Comment by wurzer** [comment]
Which operation system are you using?
Is file transfer working?

**Comment by rubencarneiro** [comment]
> Which operation system are you using?
> Is file transfer working?

Ubuntu 20.04, and file transfer works, but rhythmbox does nota recognize the decide, wile other devoções does.
